<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Problem Formulation – Introduction to Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-wrangling.html" rel="next">
<link href="./04-python.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c935fea28ce5a425f876bb828138d8e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-formulation.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Problem Formulation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/statds/ids-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preliminaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Project Management</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reproducible Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Python Practice</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-formulation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Problem Formulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Preparation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modeling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-ethics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Ethics</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-formulation-checks" id="toc-sec-formulation-checks" class="nav-link active" data-scroll-target="#sec-formulation-checks"><span class="header-section-number">5.1</span> Introduction</a></li>
  <li><a href="#interpreting-the-nypd-311-records" id="toc-interpreting-the-nypd-311-records" class="nav-link" data-scroll-target="#interpreting-the-nypd-311-records"><span class="header-section-number">5.2</span> Interpreting the NYPD 311 Records</a></li>
  <li><a href="#acquiring-and-importing-data" id="toc-acquiring-and-importing-data" class="nav-link" data-scroll-target="#acquiring-and-importing-data"><span class="header-section-number">5.3</span> Acquiring and Importing Data</a>
  <ul class="collapse">
  <li><a href="#importing-the-archive" id="toc-importing-the-archive" class="nav-link" data-scroll-target="#importing-the-archive"><span class="header-section-number">5.3.1</span> Importing the Archive</a></li>
  </ul></li>
  <li><a href="#sec-initial-checks" id="toc-sec-initial-checks" class="nav-link" data-scroll-target="#sec-initial-checks"><span class="header-section-number">5.4</span> Checking Data</a></li>
  <li><a href="#efficient-representation" id="toc-efficient-representation" class="nav-link" data-scroll-target="#efficient-representation"><span class="header-section-number">5.5</span> Efficient Representation</a></li>
  <li><a href="#provenance-and-responsibility" id="toc-provenance-and-responsibility" class="nav-link" data-scroll-target="#provenance-and-responsibility"><span class="header-section-number">5.6</span> Provenance and Responsibility</a></li>
  <li><a href="#sec-problem-detail-counts" id="toc-sec-problem-detail-counts" class="nav-link" data-scroll-target="#sec-problem-detail-counts"><span class="header-section-number">5.7</span> Revising Questions from the Checked Data</a></li>
  <li><a href="#a-working-formulation" id="toc-a-working-formulation" class="nav-link" data-scroll-target="#a-working-formulation"><span class="header-section-number">5.8</span> A Working Formulation</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/statds/ids-book/edit/main/05-formulation.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/statds/ids-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-problem-formulation" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Problem Formulation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Problem formulation connects a domain purpose, available evidence, and a question the evidence can address. This chapter develops that connection through New York City’s 311 service requests directed to the New York City Police Department (NYPD) during the week containing Labor Day 2026. The available extract is the starting point: its categories and quality checks guide the choice and refinement of an illegal-parking question. Domain context and documentation determine what the resulting analysis can establish.</p>
<p>Before running this chapter’s code, update the local book source and its Python environment so that both match the current version. From the repository directory, pull the latest changes, activate the book’s <code>.ids</code> environment, and install the pinned requirements:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> pull</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">source</span> .ids/bin/activate</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">make</span> install</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>On Windows, activate <code>.ids/Scripts/activate</code> from Git Bash. Keep the environment active while running the chapter’s code.</p>
<section id="sec-formulation-checks" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-formulation-checks"><span class="header-section-number">5.1</span> Introduction</h2>
<p>Problem formulation can begin with a domain problem or an available dataset, but either route must connect a substantive purpose to evidence capable of addressing it. Administrative records are often created to operate a service, then made available for analysis before any research question has been chosen. Their categories, times, locations, and unusual values can suggest questions that an investigator would not have formulated in advance. In this chapter, the NYPD extract’s distribution of reported problems motivates illegal parking as a working topic; a domain purpose and account of what these service requests measure determine whether a resulting question is worth pursuing.</p>
<p>The question-to-data route begins with a concern and seeks suitable evidence. A transportation planner might ask where blocked bicycle lanes are reported and then search for records with the necessary location and problem fields. The data-to-question route begins by inspecting records and asking which observed variation warrants investigation. Both routes require iteration: questions direct further inspection, and the meaning and limitations of the data can change the questions. A pattern noticed while inspecting data remains exploratory until domain knowledge, alternative explanations, and further evidence have been considered. <span class="citation" data-cites="yu2024veridical">Yu &amp; Barter (<a href="#ref-yu2024veridical" role="doc-biblioref">2024</a>)</span> describe this movement among questions, data, and analysis as a nonlinear data science life cycle. The present example begins with an administrative extract that was collected for service operations rather than for the proposed comparison. The analyst must therefore establish a domain purpose for any pattern found in the file and revise the question if the recorded fields do not represent the desired concept. This sequence keeps the data-to-question route connected to the intended use of an answer.</p>
<p>The first activity in the data-science workflow aligns three components:</p>
<ol type="1">
<li><strong>Domain purpose:</strong> Why would an answer matter, and who might use it?</li>
<li><strong>Question:</strong> What description, comparison, prediction, or decision is sought?</li>
<li><strong>Data:</strong> What was observed, how was it measured, and what setting does it represent?</li>
</ol>
<p>This alignment makes the <span class="math inline">\(D\)</span> in the <span class="math inline">\(SDC^3\)</span> formulation operational. Domain knowledge gives recorded values their meaning and identifies comparisons of interest. Statistics clarifies which claims the observations can support. Computing enables acquisition and inspection, while collaboration and communication expose assumptions that one investigator might overlook.</p>
<p>A candidate question becomes researchable when its unit, outcome, place, period, comparison, and intended claim are explicit. For this chapter, the broad topic of illegal parking can be narrowed to NYPD-directed 311 service requests, their reported problem details and closure times, and the week containing Labor Day 2026. The provisional question is: among NYPD-directed illegal-parking requests from this week, how did recorded closure-time distributions vary across reported problem details? The comparison is exploratory because the groups will be selected after inspecting the records, and it will require revision if the detail labels or closure timestamps do not measure the intended concepts. Each restriction should serve a domain purpose because the resulting conclusion applies only to the selected records.</p>
<p>Four complementary checks assess whether a candidate question is worth pursuing and whether the available evidence can answer it.</p>
<ul>
<li><strong>Domain fit</strong> asks whether an answer would inform a substantive concern or decision, and who could use it. A data-first question needs a domain purpose just as a problem-first question needs evidence suited to its purpose.</li>
<li><strong>Measurement fit</strong> asks whether the recorded variables represent the concepts in the question. For example, the NYPD records measure time to administrative closure; without further documentation, they do not measure time to an officer’s arrival.</li>
<li><strong>Scope fit</strong> asks whether the observational unit, population, place, and period match the intended claim. This extract contains NYPD-directed requests from one week, not every parking condition in New York City.</li>
<li><strong>Evidence fit</strong> asks whether the study design supports the proposed descriptive, comparative, predictive, or causal claim. A difference in recorded closure times can describe these requests, but it does not by itself show that problem type caused a difference.</li>
</ul>
<p>These checks are iterative rather than a one-time screen. A domain concern may lead to a data search, while an observed pattern may suggest a new question; in either direction, checking measurement, scope, and evidence can require revising the question. The sections that follow evaluate the provisional comparison against the downloaded records and refine it in light of what those records can establish.</p>
</section>
<section id="interpreting-the-nypd-311-records" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="interpreting-the-nypd-311-records"><span class="header-section-number">5.2</span> Interpreting the NYPD 311 Records</h2>
<p>The observational unit in this chapter is one New York City 311 service request directed to NYPD. The public dataset records requests routed to responding agencies, and its <code>Unique Key</code> field identifies rows <span class="citation" data-cites="nycopendatand311">(<a href="#ref-nycopendatand311" role="doc-biblioref">NYC Open Data, n.d.</a>)</span>. A row is neither an independently verified violation nor necessarily a unique street condition: several requests may concern the same situation, while other conditions may never be reported. Request counts therefore measure activity recorded by this service system within a defined scope. A location with few requests may have fewer conditions, less use of 311, or both; the table alone cannot separate those explanations. The identifier must be present and unique if each row is to represent one request in subsequent counts. The downloaded records must also be checked against the stated agency and time restrictions before the illegal-parking problem filter defines the working subset.</p>
<p>The timestamp fields define an administrative interval rather than a direct measure of field response. <code>Created Date</code> records the creation of a request, and <code>Closed Date</code> records its closure by the responding agency; their difference is the recorded <strong>closure time</strong>. An officer could arrive before that closure, and the reported condition could end at another time. The archive does not contain observations of those events, so relabeling the difference as response or resolution time would change the measured concept without evidence. The timestamps in this extract are local New York clock times without an explicit timezone. The selected week does not cross a daylight-saving transition, which avoids one source of ambiguity in subtracting its recorded times but does not validate each timestamp. An analysis of individual reporting behavior would additionally require information about reporters that the public table does not provide.</p>
<p>Variable roles depend on the question and the geographic concept being represented. <code>Borough</code> can define broad comparison groups, while <code>Problem Detail (formerly Descriptor)</code> distinguishes reported categories within illegal parking. <code>Unique Key</code> identifies a request and <code>Incident Zip</code> identifies a postal area; their digits are labels rather than measured magnitudes and should be imported as text. Latitude and longitude locate a recorded incident point, whereas a police precinct code refers to an administrative unit. A coordinate, precinct, and ZIP label can disagree or be missing because they are recorded through different fields and describe different spatial objects. These distinctions govern later preparation: an area merge can use a ZIP label, but a point-to-precinct distance requires a usable coordinate, a precinct location, and a defined distance metric. Treating all geographic fields as interchangeable would conceal both coverage limits and the units of the resulting analysis.</p>
</section>
<section id="acquiring-and-importing-data" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="acquiring-and-importing-data"><span class="header-section-number">5.3</span> Acquiring and Importing Data</h2>
<p>Data acquisition obtains evidence while preserving enough information to interpret and reproduce it. Common sources include local files, public repositories, open-data portals, application programming interfaces (APIs), databases, surveys, experiments, sensors, and administrative systems. The method should match the source and intended use. A stable file is convenient for a fixed classroom or research example, while an API or database query is more appropriate when an analysis must refresh regularly.</p>
<p>A reproducible acquisition records the source and the intended selection rules. The example file came from the NYC Open Data portal, where we attempted to download NYPD requests created during the week containing Labor Day 2026. The portal identifier <code>erm2-nwe9</code> locates the full 311 dataset and can be used to find its documentation or construct an API request; it is a source identifier, not a request-level key. The archive contains the returned records but not a saved copy of the portal query settings, so the intended filters and the delivered values must be checked separately.</p>
<p>The delivered file does not match the intended time window: it contains 1,902 records created during the first eight hours of September 13. This discrepancy shows why a successful download is not evidence that the portal returned exactly the requested data. The intended agency restriction also requires an independent check against the <code>Agency</code> values in the file.</p>
<p>Raw and derived data serve different purposes. The downloaded source extract preserves what the provider returned. The smaller illegal-parking data frame will be derived in code by applying the intended time restriction and then a problem-category filter while retaining all 44 source columns. Preserving the source makes it possible to audit or revise both filters. The source file should not be edited manually to remove the extra records.</p>
<p>The book distributes the downloaded CSV in a ZIP archive:</p>
<pre class="text"><code>data/311_nypd_lbdwk_2026.csv.zip</code></pre>
<p>The archive contains one CSV file and reduces its size by about 90% without changing the tabular source representation. Pandas can decompress a single-member ZIP archive during import. The filename identifies the service, agency, period, and year without depending on spaces or punctuation that require shell quoting. A companion provenance record should carry details that cannot fit sensibly in a filename, including the direct source, access date, requested selection rules, and observed departure from those rules.</p>
<section id="importing-the-archive" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="importing-the-archive"><span class="header-section-number">5.3.1</span> Importing the Archive</h3>
<p>Reproducible import begins with a project-relative path. A relative path works after another reader clones or moves the project because it describes the file’s location inside the project rather than its location on one person’s computer. The <code>Path</code> class also provides portable operations for checking and measuring the file.</p>
<div id="45e90104" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> zipfile <span class="im">import</span> ZipFile</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>data_path <span class="op">=</span> Path(<span class="st">"data"</span>) <span class="op">/</span> <span class="st">"311_nypd_lbdwk_2026.csv.zip"</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> data_path.exists():</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">FileNotFoundError</span>(data_path)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> ZipFile(data_path) <span class="im">as</span> archive:</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    members <span class="op">=</span> archive.infolist()</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">len</span>(members) <span class="op">!=</span> <span class="dv">1</span>:</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"The data archive must contain exactly one CSV file."</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>csv_member <span class="op">=</span> members[<span class="dv">0</span>]</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>file_summary <span class="op">=</span> pd.DataFrame({</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"representation"</span>: [<span class="st">"ZIP archive"</span>, <span class="st">"Uncompressed CSV"</span>],</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"size_mib"</span>: [</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>        data_path.stat().st_size <span class="op">/</span> <span class="dv">2</span><span class="op">**</span><span class="dv">20</span>,</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>        csv_member.file_size <span class="op">/</span> <span class="dv">2</span><span class="op">**</span><span class="dv">20</span>,</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>file_summary.<span class="bu">round</span>({<span class="st">"size_mib"</span>: <span class="dv">2</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">representation</th>
<th data-quarto-table-cell-role="th">size_mib</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>ZIP archive</td>
<td>4.47</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Uncompressed CSV</td>
<td>43.58</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The import specification should express meaning that cannot be inferred safely from the characters in the file. The two identifiers are read as strings, and the large mixed table is read in one pass before the date fields are converted with an explicit format.</p>
<div id="3b274d22" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>identifier_types <span class="op">=</span> {</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Unique Key"</span>: <span class="st">"string"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Incident Zip"</span>: <span class="st">"string"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>requests <span class="op">=</span> pd.read_csv(</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    data_path,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    compression<span class="op">=</span><span class="st">"zip"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    dtype<span class="op">=</span>identifier_types,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    low_memory<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>date_format <span class="op">=</span> <span class="st">"%m/</span><span class="sc">%d</span><span class="st">/%Y %I:%M:%S %p"</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column <span class="kw">in</span> [<span class="st">"Created Date"</span>, <span class="st">"Closed Date"</span>]:</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    requests[column] <span class="op">=</span> pd.to_datetime(</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>        requests[column],</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>        <span class="bu">format</span><span class="op">=</span>date_format,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>        errors<span class="op">=</span><span class="st">"coerce"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The explicit datetime format documents the month-day-year order, 12-hour clock, seconds, and morning or afternoon marker. The <code>errors="coerce"</code> argument converts an invalid timestamp to a missing datetime rather than silently leaving a mixture of strings and dates. That choice makes conversion failures countable, but it does not make them harmless; every failure should be investigated.</p>
<p>Compact inspection reveals the structure without flooding the document with 44 columns or thousands of rows. The next chunks report the dimensions and display a small selection of fields that describe time, category, and geography.</p>
<div id="91f126c7" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame({</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"rows"</span>: [requests.shape[<span class="dv">0</span>]],</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"columns"</span>: [requests.shape[<span class="dv">1</span>]],</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"memory_mib"</span>: [requests.memory_usage(deep<span class="op">=</span><span class="va">True</span>).<span class="bu">sum</span>() <span class="op">/</span> <span class="dv">2</span><span class="op">**</span><span class="dv">20</span>],</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>}).<span class="bu">round</span>({<span class="st">"memory_mib"</span>: <span class="dv">2</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">rows</th>
<th data-quarto-table-cell-role="th">columns</th>
<th data-quarto-table-cell-role="th">memory_mib</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>41955</td>
<td>44</td>
<td>49.95</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="d7bfd1e5" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>display_columns <span class="op">=</span> [</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Unique Key"</span>,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Created Date"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Problem (formerly Complaint Type)"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Problem Detail (formerly Descriptor)"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Incident Zip"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Borough"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Status"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>requests.loc[:, display_columns].head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Unique Key</th>
<th data-quarto-table-cell-role="th">Created Date</th>
<th data-quarto-table-cell-role="th">Problem (formerly Complaint Type)</th>
<th data-quarto-table-cell-role="th">Problem Detail (formerly Descriptor)</th>
<th data-quarto-table-cell-role="th">Incident Zip</th>
<th data-quarto-table-cell-role="th">Borough</th>
<th data-quarto-table-cell-role="th">Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>70401315</td>
<td>2026-09-13 07:59:16</td>
<td>Illegal Parking</td>
<td>Blocked Hydrant</td>
<td>11364</td>
<td>QUEENS</td>
<td>Closed</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>70406555</td>
<td>2026-09-13 07:59:00</td>
<td>Illegal Parking</td>
<td>Posted Parking Sign Violation</td>
<td>11239</td>
<td>BROOKLYN</td>
<td>Closed</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>70406435</td>
<td>2026-09-13 07:58:55</td>
<td>Illegal Parking</td>
<td>Blocked Hydrant</td>
<td>11229</td>
<td>BROOKLYN</td>
<td>Closed</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>70399546</td>
<td>2026-09-13 07:57:00</td>
<td>Noise - Residential</td>
<td>Banging/Pounding</td>
<td>11214</td>
<td>BROOKLYN</td>
<td>Closed</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>70405433</td>
<td>2026-09-13 07:56:08</td>
<td>Illegal Parking</td>
<td>Posted Parking Sign Violation</td>
<td>11239</td>
<td>BROOKLYN</td>
<td>Closed</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The in-memory size differs from the file size because a CSV stores characters, whereas pandas allocates objects and typed arrays needed for computation. File size and memory use answer different questions: the former affects storage and transfer, while the latter affects whether an analysis fits comfortably in a running process.</p>
<p>The preceding Python chapter introduced data frames as tables with named columns. Here, <code>requests</code> is a data frame, while an expression such as <code>requests["Agency"]</code> selects one column as a Series. A comparison on that Series produces a Boolean mask; <code>.loc[mask]</code> selects the matching rows, and <code>.copy()</code> creates a separate analysis object. The checks below also use <code>.isna().sum()</code> to count missing values and <code>.value_counts()</code> to count categories. These operations connect the import to a documented row selection without changing the downloaded data.</p>
</section>
</section>
<section id="sec-initial-checks" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-initial-checks"><span class="header-section-number">5.4</span> Checking Data</h2>
<p>Basic checks test whether the imported object matches its stated scope before any values are cleaned or transformed. They do not prove that every record is correct. Instead, they turn assumptions about the extract into results that can be reviewed. The governing principle is to trust the provider while verifying every condition on which the analysis depends.</p>
<p>The first checks address identity, agency, and both temporal boundaries. A portal selection is an instruction about what to return; these checks test whether the delivered records satisfy it. For the Sunday-through-Saturday week, the intended creation-time window begins at midnight on September 6 and ends immediately before midnight on September 13. The inclusive lower bound and exclusive upper bound include every timestamp on the seven intended days without ambiguity at the next week’s boundary.</p>
<div id="8da89b09" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> pd.Timestamp(<span class="st">"2026-09-06"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>end <span class="op">=</span> pd.Timestamp(<span class="st">"2026-09-13"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>valid_created <span class="op">=</span> requests[<span class="st">"Created Date"</span>].notna()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>in_intended_week <span class="op">=</span> requests[<span class="st">"Created Date"</span>].between(</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    start, end, inclusive<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>agency_mismatch <span class="op">=</span> requests[<span class="st">"Agency"</span>].isna() <span class="op">|</span> <span class="op">~</span>requests[<span class="st">"Agency"</span>].eq(<span class="st">"NYPD"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>before_start <span class="op">=</span> valid_created <span class="op">&amp;</span> requests[<span class="st">"Created Date"</span>].lt(start)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>on_or_after_end <span class="op">=</span> valid_created <span class="op">&amp;</span> requests[<span class="st">"Created Date"</span>].ge(end)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>outside_intended_week <span class="op">=</span> before_start <span class="op">|</span> on_or_after_end</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>scope_checks <span class="op">=</span> pd.Series({</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"rows delivered"</span>: <span class="bu">len</span>(requests),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"missing unique keys"</span>: requests[<span class="st">"Unique Key"</span>].isna().<span class="bu">sum</span>(),</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"duplicated unique keys"</span>: requests[<span class="st">"Unique Key"</span>].duplicated().<span class="bu">sum</span>(),</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"agency mismatches"</span>: agency_mismatch.<span class="bu">sum</span>(),</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"agency values"</span>: requests[<span class="st">"Agency"</span>].nunique(dropna<span class="op">=</span><span class="va">False</span>),</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"invalid created dates"</span>: requests[<span class="st">"Created Date"</span>].isna().<span class="bu">sum</span>(),</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"created before week"</span>: before_start.<span class="bu">sum</span>(),</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"created at or after next week"</span>: on_or_after_end.<span class="bu">sum</span>(),</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>}, name<span class="op">=</span><span class="st">"value"</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>scope_checks.to_frame()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">rows delivered</th>
<td>41955</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">missing unique keys</th>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">duplicated unique keys</th>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">agency mismatches</th>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">agency values</th>
<td>1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">invalid created dates</th>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">created before week</th>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">created at or after next week</th>
<td>1902</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The returned agency values and date-boundary counts show whether the file matches the intended selection on both dimensions. The frequency table provides the actual agency labels, while the separate lower- and upper-bound counts identify which side of the time window failed.</p>
<div id="ec22be78" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame({</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"agency"</span>: requests[<span class="st">"Agency"</span>].value_counts(dropna<span class="op">=</span><span class="va">False</span>),</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">agency</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Agency</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">NYPD</th>
<td>41955</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="42fba037" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame({</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"earliest"</span>: [requests[<span class="st">"Created Date"</span>].<span class="bu">min</span>()],</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"latest"</span>: [requests[<span class="st">"Created Date"</span>].<span class="bu">max</span>()],</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">earliest</th>
<th data-quarto-table-cell-role="th">latest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>2026-09-06 00:00:04</td>
<td>2026-09-13 07:59:16</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The analysis subset should be created only after the discrepancy has been measured and reported. The half-open interval removes 1,902 records returned outside the requested week without changing the downloaded object.</p>
<div id="0d1513a6" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>week_requests <span class="op">=</span> requests.loc[in_intended_week].copy()</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>pd.Series({</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"rows delivered"</span>: <span class="bu">len</span>(requests),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"rows in intended week"</span>: <span class="bu">len</span>(week_requests),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"rows removed by time check"</span>: <span class="bu">len</span>(requests) <span class="op">-</span> <span class="bu">len</span>(week_requests),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>}, name<span class="op">=</span><span class="st">"requests"</span>).to_frame()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">requests</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">rows delivered</th>
<td>41955</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">rows in intended week</th>
<td>40053</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">rows removed by time check</th>
<td>1902</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The problem frequency table reveals what the screened week contains and makes the next analytical choice visible. Illegal parking is the largest category, but it accounts for only about one-third of the NYPD requests.</p>
<div id="a57daacd" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>problem_column <span class="op">=</span> <span class="st">"Problem (formerly Complaint Type)"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>problem_counts <span class="op">=</span> (</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    week_requests[problem_column]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    .value_counts(dropna<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    .rename_axis(<span class="st">"problem"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    .reset_index(name<span class="op">=</span><span class="st">"requests"</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>problem_counts</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">problem</th>
<th data-quarto-table-cell-role="th">requests</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Illegal Parking</td>
<td>13040</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Noise - Residential</td>
<td>8368</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Noise - Street/Sidewalk</td>
<td>6733</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Blocked Driveway</td>
<td>3960</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Noise - Commercial</td>
<td>1542</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Abandoned Vehicle</td>
<td>1494</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Noise - Vehicle</td>
<td>1440</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Encampment</td>
<td>1162</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Non-Emergency Police Matter</td>
<td>568</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Noise - Park</td>
<td>368</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Panhandling</td>
<td>321</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Drug Activity</td>
<td>192</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>Illegal Fireworks</td>
<td>188</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>Animal-Abuse</td>
<td>188</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>Traffic</td>
<td>164</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>Drinking</td>
<td>147</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>Urinating in Public</td>
<td>57</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>Bike/Roller/Skate</td>
<td>57</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>Noise - House of Worship</td>
<td>39</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>Graffiti</td>
<td>18</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">20</th>
<td>Posting Advertisement</td>
<td>5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">21</th>
<td>Disorderly Youth</td>
<td>2</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The working subset retains only the illegal-parking requests from the intended week. Its 13,040 rows and 44 columns are consequences of two documented filters, not properties assumed from the filename.</p>
<div id="04f9ca16" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>parking <span class="op">=</span> week_requests.loc[</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    week_requests[problem_column].eq(<span class="st">"Illegal Parking"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>parking.shape</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>(13040, 44)</code></pre>
</div>
</div>
<p>Missingness should be summarized before it is treated. A column can be absent because the field does not apply to this kind of request, because the value was unknown, or because it was lost. Those mechanisms have different meanings, so a missing-value count is the beginning of an investigation rather than a cleaning instruction.</p>
<div id="86094d42" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>missingness <span class="op">=</span> (</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    pd.DataFrame({</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"missing"</span>: parking.isna().<span class="bu">sum</span>(),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="st">"percent"</span>: parking.isna().mean().mul(<span class="dv">100</span>),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    .query(<span class="st">"missing &gt; 0"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    .sort_values([<span class="st">"percent"</span>, <span class="st">"missing"</span>], ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>missingness.<span class="bu">round</span>({<span class="st">"percent"</span>: <span class="dv">2</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">missing</th>
<th data-quarto-table-cell-role="th">percent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Facility Type</th>
<td>13040</td>
<td>100.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Due Date</th>
<td>13040</td>
<td>100.00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Taxi Company Borough</th>
<td>13040</td>
<td>100.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Taxi Pick Up Location</th>
<td>13040</td>
<td>100.00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Bridge Highway Name</th>
<td>13040</td>
<td>100.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Bridge Highway Direction</th>
<td>13040</td>
<td>100.00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Road Ramp</th>
<td>13040</td>
<td>100.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Bridge Highway Segment</th>
<td>13040</td>
<td>100.00</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Additional Details</th>
<td>12575</td>
<td>96.43</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Vehicle Type</th>
<td>11996</td>
<td>91.99</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">BBL</th>
<td>1570</td>
<td>12.04</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">City</th>
<td>1066</td>
<td>8.17</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Landmark</th>
<td>1066</td>
<td>8.17</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Council District</th>
<td>99</td>
<td>0.76</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">X Coordinate (State Plane)</th>
<td>99</td>
<td>0.76</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Y Coordinate (State Plane)</th>
<td>99</td>
<td>0.76</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Latitude</th>
<td>99</td>
<td>0.76</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Longitude</th>
<td>99</td>
<td>0.76</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Location</th>
<td>99</td>
<td>0.76</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Cross Street 1</th>
<td>23</td>
<td>0.18</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Intersection Street 1</th>
<td>23</td>
<td>0.18</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Cross Street 2</th>
<td>6</td>
<td>0.05</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Intersection Street 2</th>
<td>6</td>
<td>0.05</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The missingness table shows that several fields do not apply to these requests, while 99 rows lack each coordinate field and council district. A pairwise check is needed before concluding that latitude and longitude are missing together.</p>
<div id="2a0ffd1d" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>coordinate_missingness <span class="op">=</span> pd.crosstab(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    parking[<span class="st">"Latitude"</span>].isna(),</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    parking[<span class="st">"Longitude"</span>].isna(),</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    rownames<span class="op">=</span>[<span class="st">"latitude missing"</span>],</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    colnames<span class="op">=</span>[<span class="st">"longitude missing"</span>],</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    dropna<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>coordinate_missingness</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">longitude missing</th>
<th data-quarto-table-cell-role="th">False</th>
<th data-quarto-table-cell-role="th">True</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">latitude missing</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">False</th>
<td>12941</td>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">True</th>
<td>0</td>
<td>99</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Nonmissing coordinate ranges can reveal misplaced decimal points, swapped coordinates, or locations far from the city. Plausible ranges do not establish that every point lies inside New York City because an exact test would require authoritative boundary geometry.</p>
<div id="25585a3f" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>parking[[<span class="st">"Latitude"</span>, <span class="st">"Longitude"</span>]].agg([<span class="st">"min"</span>, <span class="st">"max"</span>]).<span class="bu">round</span>(<span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Latitude</th>
<th data-quarto-table-cell-role="th">Longitude</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">min</th>
<td>40.499721</td>
<td>-74.249314</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">max</th>
<td>40.911354</td>
<td>-73.701308</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Related fields provide opportunities to test internal consistency. Nearly all rows have status <code>Closed</code>, while one row has status <code>Unspecified</code>. Every row, including that exception, has a closing timestamp. The discrepancy is evidence to report, not permission to replace the status automatically.</p>
<div id="543c7b82" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>pd.crosstab(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    parking[<span class="st">"Status"</span>],</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    parking[<span class="st">"Closed Date"</span>].isna(),</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    rownames<span class="op">=</span>[<span class="st">"status"</span>],</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    colnames<span class="op">=</span>[<span class="st">"closed date missing"</span>],</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    dropna<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">closed date missing</th>
<th data-quarto-table-cell-role="th">False</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">status</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Closed</th>
<td>13039</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Unspecified</th>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Chronological checks can identify impossible or ambiguous records. The next calculation verifies that no closing time precedes its creation time and summarizes the derived closure time without adding it permanently to the source-derived data frame.</p>
<div id="c2a2708e" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>closure_hours <span class="op">=</span> (</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    parking[<span class="st">"Closed Date"</span>] <span class="op">-</span> parking[<span class="st">"Created Date"</span>]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>).dt.total_seconds() <span class="op">/</span> <span class="dv">3600</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>pd.DataFrame({</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"missing"</span>: [closure_hours.isna().<span class="bu">sum</span>()],</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"negative"</span>: [(closure_hours <span class="op">&lt;</span> <span class="dv">0</span>).<span class="bu">sum</span>()],</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"median_hours"</span>: [closure_hours.median()],</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"mean_hours"</span>: [closure_hours.mean()],</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"maximum_hours"</span>: [closure_hours.<span class="bu">max</span>()],</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>}).<span class="bu">round</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">missing</th>
<th data-quarto-table-cell-role="th">negative</th>
<th data-quarto-table-cell-role="th">median_hours</th>
<th data-quarto-table-cell-role="th">mean_hours</th>
<th data-quarto-table-cell-role="th">maximum_hours</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>1.67</td>
<td>3.5</td>
<td>199.83</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The long upper tail makes the mean much larger than the median. That pattern is worth exploring later, but basic checking already prevents a misleading label: the computation measures time to recorded closure, not necessarily time to an officer’s arrival or resolution of the reported condition.</p>
<p>Unusual concentrations at exact times can expose rounding, default values, or batch processing. Tussey and Yan use temporal and logical checks of this kind in their case study of NYC 311 data curation <span class="citation" data-cites="tussey2025principles">(<a href="#ref-tussey2025principles" role="doc-biblioref">Tussey &amp; Yan, 2025</a>)</span>. The diagnostic should be repeated on each extract rather than assumed to produce the same result everywhere.</p>
<div id="fcca4286" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>created <span class="op">=</span> parking[<span class="st">"Created Date"</span>].dropna()</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>closed <span class="op">=</span> parking[<span class="st">"Closed Date"</span>].dropna()</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>time_heaping <span class="op">=</span> pd.Series({</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"created exactly at midnight"</span>: (</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>        (created.dt.hour <span class="op">==</span> <span class="dv">0</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>        <span class="op">&amp;</span> (created.dt.minute <span class="op">==</span> <span class="dv">0</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>        <span class="op">&amp;</span> (created.dt.second <span class="op">==</span> <span class="dv">0</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>    ).<span class="bu">sum</span>(),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"created exactly on an hour"</span>: (</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>        (created.dt.minute <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (created.dt.second <span class="op">==</span> <span class="dv">0</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    ).<span class="bu">sum</span>(),</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"closed exactly at midnight"</span>: (</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>        (closed.dt.hour <span class="op">==</span> <span class="dv">0</span>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>        <span class="op">&amp;</span> (closed.dt.minute <span class="op">==</span> <span class="dv">0</span>)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>        <span class="op">&amp;</span> (closed.dt.second <span class="op">==</span> <span class="dv">0</span>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>    ).<span class="bu">sum</span>(),</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"closed exactly on an hour"</span>: (</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>        (closed.dt.minute <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (closed.dt.second <span class="op">==</span> <span class="dv">0</span>)</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>    ).<span class="bu">sum</span>(),</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"closure time is a whole hour"</span>: (</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>        closure_hours.mod(<span class="dv">1</span>).<span class="bu">abs</span>() <span class="op">&lt;</span> <span class="fl">1e-12</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>    ).<span class="bu">sum</span>(),</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>}, name<span class="op">=</span><span class="st">"requests"</span>)</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>time_heaping.to_frame()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">requests</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">created exactly at midnight</th>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">created exactly on an hour</th>
<td>4</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">closed exactly at midnight</th>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">closed exactly on an hour</th>
<td>10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">closure time is a whole hour</th>
<td>4</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This one-week illegal-parking subset contains no creation or closing timestamps exactly at midnight. Only four creation times and ten closing times fall exactly on an hour, and four closure durations equal a whole number of hours. The large concentration reported for the longer multi-agency dataset is therefore not present here. Its absence does not invalidate a problem found in a larger or different extract; it shows why a quality report must identify the agency, variables, and time period checked.</p>
</section>
<section id="efficient-representation" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="efficient-representation"><span class="header-section-number">5.5</span> Efficient Representation</h2>
<p>Data representation affects storage, import time, type preservation, and interoperability. The CSV format is widely supported text that is easy to inspect with ordinary tools. Its simplicity is valuable for acquisition and archival exchange, but each reader must parse the text and reconstruct such types as datetimes and identifiers.</p>
<p>Apache Arrow defines a column-oriented representation designed for efficient analytical data interchange across systems. Feather Version 2 stores Arrow’s interprocess communication format in a portable file and supports typed columns and compression <span class="citation" data-cites="apache2026feather">(<a href="#ref-apache2026feather" role="doc-biblioref">Apache Arrow Developers, 2026</a>)</span>. Bates and Yan describe how an Arrow representation can create a unified dataset for efficient analysis across software platforms <span class="citation" data-cites="bates2024from">(<a href="#ref-bates2024from" role="doc-biblioref">Bates &amp; Yan, 2024</a>)</span>.</p>
<p>A derived Feather file can preserve the imported table’s typed representation for repeated analysis. The example writes to a temporary directory so that rendering the chapter does not add a generated file to the project.</p>
<div id="102d9c8c" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tempfile <span class="im">import</span> TemporaryDirectory</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> TemporaryDirectory() <span class="im">as</span> temporary_directory:</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    feather_path <span class="op">=</span> Path(temporary_directory) <span class="op">/</span> <span class="st">"nypd_download.feather"</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    requests.to_feather(feather_path)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    requests_from_feather <span class="op">=</span> pd.read_feather(feather_path)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>    representation <span class="op">=</span> pd.DataFrame({</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"format"</span>: [<span class="st">"CSV"</span>, <span class="st">"ZIP-compressed CSV"</span>, <span class="st">"Feather"</span>],</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"size_mib"</span>: [</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>            csv_member.file_size <span class="op">/</span> <span class="dv">2</span><span class="op">**</span><span class="dv">20</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>            data_path.stat().st_size <span class="op">/</span> <span class="dv">2</span><span class="op">**</span><span class="dv">20</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>            feather_path.stat().st_size <span class="op">/</span> <span class="dv">2</span><span class="op">**</span><span class="dv">20</span>,</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>representation.<span class="bu">round</span>({<span class="st">"size_mib"</span>: <span class="dv">2</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">format</th>
<th data-quarto-table-cell-role="th">size_mib</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>CSV</td>
<td>43.58</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>ZIP-compressed CSV</td>
<td>4.47</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Feather</td>
<td>10.32</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The ZIP archive is smaller than the Feather file in this example. Efficient representation does not mean smallest file under every criterion: ZIP applies strong general-purpose compression to text, while Feather preserves a typed, column-oriented representation designed for analytical access. Storage size, read time, type preservation, and cross-platform use should therefore be compared separately.</p>
<p>The round trip should preserve the shape, values, and important types. Separate checks make failures easier to diagnose than one large comparison whose false result gives no explanation.</p>
<div id="5eb77cc4" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>pd.Series({</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"same shape"</span>: requests.shape <span class="op">==</span> requests_from_feather.shape,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"same columns"</span>: requests.columns.equals(requests_from_feather.columns),</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"same values and types"</span>: requests.equals(requests_from_feather),</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>}, name<span class="op">=</span><span class="st">"check"</span>).to_frame()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">check</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">same shape</th>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">same columns</th>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">same values and types</th>
<td>True</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The screened illegal-parking data can also be stored as a typed analysis dataset. Filtering retains row-index labels from the downloaded table, but <code>Unique Key</code> is the request identifier; the inherited index labels have no analytical meaning. Resetting them before writing Feather gives the derived table a regular row index without changing its 44 source columns.</p>
<div id="a25b72a2" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>parking_for_feather <span class="op">=</span> parking.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> TemporaryDirectory() <span class="im">as</span> temporary_directory:</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    parking_path <span class="op">=</span> Path(temporary_directory) <span class="op">/</span> <span class="st">"illegal_parking.feather"</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    parking_for_feather.to_feather(parking_path)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    parking_from_feather <span class="op">=</span> pd.read_feather(parking_path)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    parking_file_checks <span class="op">=</span> pd.DataFrame({</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"rows"</span>: [<span class="bu">len</span>(parking_from_feather)],</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"columns"</span>: [<span class="bu">len</span>(parking_from_feather.columns)],</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"size_mib"</span>: [parking_path.stat().st_size <span class="op">/</span> <span class="dv">2</span><span class="op">**</span><span class="dv">20</span>],</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"same_values_and_types"</span>: [</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>            parking_for_feather.equals(parking_from_feather)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>        ],</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>parking_file_checks.<span class="bu">round</span>({<span class="st">"size_mib"</span>: <span class="dv">2</span>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">rows</th>
<th data-quarto-table-cell-role="th">columns</th>
<th data-quarto-table-cell-role="th">size_mib</th>
<th data-quarto-table-cell-role="th">same_values_and_types</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>13040</td>
<td>44</td>
<td>3.19</td>
<td>True</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The temporary file demonstrates the conversion without creating an output during book rendering. A persistent copy for later analysis should record both filters, the source archive, and the conversion choices in its provenance.</p>
<p>Performance comparisons require more care than a single stopwatch reading. Operating-system caching, storage hardware, background activity, parsing options, and compression can change the result. A fair comparison repeats each operation, reports a robust summary such as the median, and includes the CSV type conversions needed by the actual analysis. The exercises ask readers to design and document that comparison.</p>
<p>Efficient formats complement rather than automatically replace source formats. The CSV member of the ZIP archive remains a broadly readable text artifact. A Feather file is useful as a typed derivative or interchange artifact when the same table is loaded repeatedly or used by multiple analytical systems. Both need provenance because a compact or compressed file does not explain where its values came from or why its rows were selected.</p>
</section>
<section id="provenance-and-responsibility" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="provenance-and-responsibility"><span class="header-section-number">5.6</span> Provenance and Responsibility</h2>
<p>Data provenance records the history needed to interpret and reproduce a dataset. A useful record names the provider, source, access date, selection rules, observational unit, temporal scope, transformations, and known limitations. It also distinguishes statements made by the provider from decisions made by the analyst.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Item</th>
<th>Record for the chapter data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Provider</td>
<td>NYC 311 through NYC Open Data</td>
</tr>
<tr class="even">
<td>Source dataset</td>
<td>311 Service Requests from 2020 to Present</td>
</tr>
<tr class="odd">
<td>Dataset identifier</td>
<td><code>erm2-nwe9</code> (portal locator for the full 311 dataset)</td>
</tr>
<tr class="even">
<td>Observational unit</td>
<td>One 311 service request</td>
</tr>
<tr class="odd">
<td>Intended portal selection</td>
<td>NYPD requests created during September 6–12, 2026</td>
</tr>
<tr class="even">
<td>Query record</td>
<td>Portal query settings were not saved with the downloaded archive</td>
</tr>
<tr class="odd">
<td>Verified agency restriction</td>
<td>Checked against the delivered <code>Agency</code> values</td>
</tr>
<tr class="even">
<td>Verified time restriction</td>
<td>Checked against both boundaries of the intended week</td>
</tr>
<tr class="odd">
<td>Delivered time coverage</td>
<td>September 6 at 00:00:04 through September 13 at 07:59:16</td>
</tr>
<tr class="even">
<td>Distributed source archive</td>
<td><code>data/311_nypd_lbdwk_2026.csv.zip</code></td>
</tr>
<tr class="odd">
<td>Local analysis filters</td>
<td>Intended half-open time interval, then <code>Problem (formerly Complaint Type) == "Illegal Parking"</code></td>
</tr>
<tr class="even">
<td>Columns retained</td>
<td>All 44 source columns</td>
</tr>
<tr class="odd">
<td>Known limitations</td>
<td>Requests are not verified incidents; reporting and closure processes are not fully observed</td>
</tr>
</tbody>
</table>
<p>File integrity can be recorded with a cryptographic hash. A matching hash shows that two copies contain the same bytes; it does not show that the data are accurate or appropriate for a question.</p>
<div id="3bbac52d" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> hashlib</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> data_path.<span class="bu">open</span>(<span class="st">"rb"</span>) <span class="im">as</span> input_file:</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    sha256 <span class="op">=</span> hashlib.file_digest(input_file, <span class="st">"sha256"</span>).hexdigest()</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>sha256</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>'a18c7ff8966fe49d57750e3fd9d4634904460824c034e32e7bb88d25ce47df5e'</code></pre>
</div>
</div>
<p>Responsible acquisition also limits unnecessary exposure. This public dataset does not identify the person who submitted a request, but it contains precise incident addresses and coordinates. An analysis that needs only ZIP Code or precinct summaries should avoid displaying individual addresses. Public availability does not eliminate the responsibility to minimize unnecessary detail and to follow the source’s terms of use.</p>
<p>Open-data curation requires more than distributing a readable file. Tussey and Yan propose six principles from their study of NYC 311: cross-organizational consistency, accurate data entry, efficient storage, current data dictionaries, automated quality assurance, and transparency <span class="citation" data-cites="tussey2025principles">(<a href="#ref-tussey2025principles" role="doc-biblioref">Tussey &amp; Yan, 2025</a>)</span>. Their examples include inconsistent representations of missing values, invalid ZIP Codes, implausible date relationships, unusual concentrations at particular times, redundant fields, and categories whose meaning varies by agency or period.</p>
<p>These findings are prompts for investigation rather than universal cleaning rules. A negative duration may reveal a timestamp error, a misunderstood field, or a clock convention. A concentration at midnight may be a default, a batch process, or a genuine operational schedule. A responsible analyst first quantifies the pattern, checks documentation and related fields, and asks the data curator when the intended meaning remains uncertain. Deleting or replacing an unusual value without that inquiry can hide the very process that needs to be understood.</p>
</section>
<section id="sec-problem-detail-counts" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="sec-problem-detail-counts"><span class="header-section-number">5.7</span> Revising Questions from the Checked Data</h2>
<p>The checked extract supports a more specific question than the download alone suggested. The intended week contains several NYPD problem categories, with illegal parking the largest. Screening the extra September 13 records fixes the time scope, while missing coordinates and the distinction between closure and response constrain the outcomes that can be interpreted. These findings direct the next inspection toward variation within illegal-parking requests.</p>
<p>The problem-detail field provides an inventory of that variation. A complete frequency table is short enough to inspect directly.</p>
<div id="74a9fe23" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>detail_counts <span class="op">=</span> (</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>    parking[<span class="st">"Problem Detail (formerly Descriptor)"</span>]</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    .value_counts(dropna<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>    .rename_axis(<span class="st">"problem detail"</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    .reset_index(name<span class="op">=</span><span class="st">"requests"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>detail_counts</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">problem detail</th>
<th data-quarto-table-cell-role="th">requests</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Blocked Hydrant</td>
<td>3711</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Posted Parking Sign Violation</td>
<td>3266</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Blocked Sidewalk</td>
<td>1874</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Commercial Overnight Parking</td>
<td>927</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Blocked Crosswalk</td>
<td>780</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Double Parked Blocking Traffic</td>
<td>672</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Parking Permit Improper Use</td>
<td>485</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Blocked Bike Lane</td>
<td>379</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Double Parked Blocking Vehicle</td>
<td>372</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>License Plate Obscured</td>
<td>269</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Unauthorized Bus Layover</td>
<td>102</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Paper License Plates</td>
<td>77</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>Overnight Commercial Storage</td>
<td>69</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>Detached Trailer</td>
<td>57</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The problem-detail table can motivate several kinds of questions, but each requires a different target and standard of evidence. A descriptive question asks which categories were most common among the selected requests. A comparative question asks whether the category distribution differed across boroughs or creation-time periods. A predictive question asks whether fields available when a request was created can predict a subsequent closure interval; it would require an evaluation on data withheld from model fitting. These questions concern recorded NYPD-directed requests rather than all illegal-parking events in the city. Domain knowledge identifies which differences matter to residents or agencies, while the intended claim determines whether additional data are necessary. The following table separates quantities that the extract can describe from the evidence required for broader operational, safety, equity, or reporting claims. It also makes the exclusion of requests handled by other agencies explicit.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Domain concern</th>
<th>Possible question</th>
<th>Evidence in this extract</th>
<th>Evidence still needed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Demand for NYPD-handled 311 services</td>
<td>When and where were illegal-parking requests concentrated during the holiday week?</td>
<td>Creation time, incident location, ZIP Code, precinct, and borough</td>
<td>Other weeks to determine whether the pattern is unusual</td>
</tr>
<tr class="even">
<td>NYPD operational workload</td>
<td>Which problem details or areas had the longest recorded closure times?</td>
<td>Creation and closure times, problem detail, and geography</td>
<td>Documentation of the NYPD closure process, staffing, assignment, and field-response times</td>
</tr>
<tr class="odd">
<td>Street access and safety</td>
<td>Where were blocked bike lanes, hydrants, sidewalks, or crosswalks frequently reported?</td>
<td>Problem detail and incident location</td>
<td>Verification of conditions, street and curb context, traffic exposure, and enforcement outcomes</td>
</tr>
<tr class="even">
<td>Geographic equity</td>
<td>Did neighborhoods differ in requests or closure times relative to their populations?</td>
<td>Request counts, ZIP Code, and closure time</td>
<td>Compatible geographic boundaries, population or exposure denominators, and evidence about reporting access</td>
</tr>
<tr class="odd">
<td>Reporting behavior</td>
<td>Did reporting patterns differ between daytime and nighttime?</td>
<td>Request creation time, channel, problem detail, and location</td>
<td>Information about who could report, unreported conditions, and alternative reporting channels</td>
</tr>
<tr class="even">
<td>Data-system quality</td>
<td>Did the delivered records satisfy the requested filters and expected logical relationships?</td>
<td>Identifiers, categories, timestamps, status, and related geographic fields</td>
<td>Portal query metadata, data-entry rules, and explanations from the data curator</td>
</tr>
</tbody>
</table>
<p>The first and last questions can be investigated directly as descriptions of this NYPD extract. The operational questions require care because closure is an administrative event, not necessarily a field response. The safety and equity questions require the most augmentation: request counts alone cannot reveal how often a condition occurred, how many people were exposed, or how likely different communities were to use 311. The extract cannot support comparisons with agencies absent from the file.</p>
<p>Domain knowledge also helps choose a useful level of detail. “Where is illegal parking a problem?” is too broad because neither <em>where</em>, <em>problem</em>, nor the relevant measure has been defined. A narrower question might ask, “During the Labor Day week, which precincts recorded the most requests about blocked fire hydrants, and did their median closure times differ?” The revision identifies the unit, category, place, period, and comparison, while still acknowledging that the result describes recorded requests rather than all blocked hydrants.</p>
<p>A final evaluation applies the domain, measurement, scope, and evidence checks to the proposed claim rather than merely to its computational form. The records may show that requests created at night have different closure times from those created during the day, but the comparison does not establish an effect of reporting time: problem detail, location, staffing, and reporting behavior may also vary with the hour. Similarly, averaging ZIP Codes after they have been imported as numbers is computationally possible but has no geographic interpretation. Raw request counts by ZIP label describe the file, yet they are not comparable as per-resident reporting rates when areas differ in population and parking opportunities. Each proposed analysis must therefore name its measured quantity, eligible requests, comparison basis, and intended inference. A causal claim would additionally require a design and assumptions that address competing explanations.</p>
<p>Additional area-level data could supply denominators and context for ZIP-level request counts. Census characteristics are often tabulated for ZIP Code Tabulation Areas (ZCTAs), which are related to postal ZIP Codes but do not represent identical geographies <span class="citation" data-cites="census2023zip">(<a href="#ref-census2023zip" role="doc-biblioref">U.S. Census Bureau, 2023</a>)</span>. <a href="06-wrangling.html#sec-zcta-context-merge" class="quarto-xref"><span>Section 6.5</span></a> demonstrates one such enrichment and evaluates its key, reference period, join cardinality, and unmatched records. Even a validated match describes places rather than the individuals who submitted requests.</p>
</section>
<section id="a-working-formulation" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="a-working-formulation"><span class="header-section-number">5.8</span> A Working Formulation</h2>
<p>A working formulation records the current alignment of purpose, target, population, and evidence while allowing later checks to revise it. The eligible population consists of NYPD-directed illegal-parking requests created during September 6–12, 2026; the outcome is each request’s recorded creation-to-closure interval in hours. The three most frequently reported problem details are <code>Blocked Hydrant</code>, <code>Posted Parking Sign Violation</code>, and <code>Blocked Sidewalk</code>. For a detail group <span class="math inline">\(g\)</span>, the descriptive target is the distribution of those closure intervals among eligible requests labeled <span class="math inline">\(g\)</span>, rather than a causal effect of the label or a citywide incident rate. Selecting groups by their observed frequencies avoids choosing them because their closure summaries appear different, but the selection still uses the same week under study. These definitions yield the working comparison:</p>
<blockquote class="blockquote">
<p>Among NYPD illegal-parking requests created from September 6 through September 12, 2026, how did recorded closure-time distributions differ among the three most frequently reported problem details?</p>
</blockquote>
<p>The working comparison has a defined unit, period, outcome, and group rule, but its interpretation remains descriptive. Groups were selected after inspecting the week’s category frequencies, and the records were collected through a reporting system rather than a probability sample of parking conditions. Location, reporting time, and agency practices may also differ among the categories. A difference between their closure-time distributions would therefore characterize these recorded requests during a holiday week; it would not identify the effect of changing a request’s problem label. Exploratory analysis can examine distribution shape and subgroup variation, while a later study could define a broader target period or collect process data to investigate the operational reasons for a difference. The present formulation makes those later requirements visible before a summary statistic or plot is chosen.</p>
<p>Other features of the checked extract support different formulations. The problem-detail table records 3,711 requests about blocked hydrants and 379 about blocked bike lanes, while 99 illegal-parking requests lack coordinates. These observations suggest several questions with distinct uses:</p>
<ol type="1">
<li>Which precincts recorded the most blocked-hydrant requests during the week, and how did their closure-time distributions differ?</li>
<li>Within each problem detail, did requests created at night have longer closure times than requests created during the day?</li>
<li>Were requests without coordinates concentrated in particular boroughs or problem details, and would their omission change a geographic summary?</li>
<li>How would the geographic pattern of blocked-bike-lane requests change if counts were compared with bicycle-lane mileage or another exposure measure?</li>
</ol>
<p>The first three questions can be investigated within this NYPD extract, though the data cannot explain the cause of a difference without further evidence. The fourth requires an additional geographic dataset and a defensible match between its areas and the request locations. Each question concerns recorded requests rather than all conditions on the street.</p>
<p>The data-to-question route remains open after these examples. What other questions do the screened records suggest? Which would inform a specific decision or deepen understanding of NYPD-directed 311 requests? For each candidate, identify the observational unit, measurements, comparison, and claim that the available evidence could support. State what additional data or domain knowledge would strengthen the answer.</p>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<p>Problems 5.1 and 5.2 establish the core analysis. Problem 5.3 is an optional curation extension that develops selected issues for later data preparation. Write one <code>.qmd</code> file containing your answers, using executable code, concise prose, and rendered tables. Put every result in the document rather than only in a terminal session: include code where computation is requested, the relevant output or a concise summary table, and a short interpretation. Do not print an entire data frame when a small sample or summary answers the question.</p>
<p>Download the <a href="https://github.com/statds/ids-book/raw/refs/heads/main/data/311_nypd_lbdwk_2026.csv.zip">supplied ZIP archive</a> into a local <code>data/</code> directory in your homework repository so the relative path in your code resolves. Do not add the archive to Git or commit it; the grader will place the same file in the corresponding path before rendering your homework. Run Quarto from the homework repository root. Keep generated data products, such as the Feather file, local as well; your code should create them when rendered.</p>
<div id="exr-import-311" class="theorem exercise">
<p><span class="theorem-title"><strong> 5.1</strong></span> Import and document the NYC 311 source extract.</p>
<ol type="a">
<li>Read the NYC Open Data source description and data dictionary. In your own words, explain what one row represents and describe <code>Unique Key</code>, <code>Problem (formerly Complaint Type)</code>, <code>Problem Detail (formerly Descriptor)</code>, <code>Created Date</code>, and <code>Closed Date</code>.</li>
<li>Construct the path to <code>data/311_nypd_lbdwk_2026.csv.zip</code> relative to the project directory. Check that the file exists, verify that it contains exactly one CSV member, and report both compressed and uncompressed sizes in MiB. Explain why a relative path is preferable to an absolute path in a reproducible analysis.</li>
<li>Import the compressed CSV file directly into a pandas data frame. Import <code>Unique Key</code> and <code>Incident Zip</code> as strings, then convert <code>Created Date</code> and <code>Closed Date</code> to datetime values using their documented format. Explain why the two identifiers should not be imported as measured numbers.</li>
<li>Report the numbers of rows and columns. Display the column names and data types, followed by a small number of rows. Do not print the entire data frame.</li>
<li>Check whether either datetime conversion produced missing values. Explain why a successful conversion does not establish that every date is correct.</li>
<li>Calculate the data frame’s memory usage and compare it with the compressed archive and uncompressed CSV sizes. Explain why the three quantities differ.</li>
<li>Store the imported data in a derived Feather file without replacing the ZIP archive. Compare the Feather, ZIP, and uncompressed CSV sizes, and calculate each percentage change relative to the uncompressed CSV.</li>
<li>Read the compressed CSV and Feather files at least five times each and record the elapsed time for every import. Use <code>time.perf_counter()</code> and report the median for each format as well as the individual timings. Ensure that the compressed CSV timing includes decompression, the identifier types, and the datetime conversions required above. Describe the timing procedure and computing environment so the comparison can be interpreted appropriately.</li>
<li>Compare the values, column names, column order, and data types obtained from the two formats. Identify information that must be reconstructed when the CSV is read and information that Feather retains.</li>
<li>Read Bates and Yan <span class="citation" data-cites="bates2024from">(<a href="#ref-bates2024from" role="doc-biblioref">2024</a>)</span>. Explain why a typed, cross-platform representation can improve computational efficiency and reproducibility. Give one reason to retain the ZIP archive containing the original CSV even when Feather is more efficient for repeated analysis.</li>
<li>Prepare a provisional provenance record containing the provider, source URL, observational unit, requested extraction criteria, access date, and known limitations. Distinguish facts documented by NYC Open Data from details reported by the person who downloaded this file. Revise the record after completing the checks in the next problem.</li>
</ol>
</div>
<div id="exr-check-311" class="theorem exercise">
<p><span class="theorem-title"><strong> 5.2</strong></span> Check the scope of the downloaded data, construct the intended illegal-parking subset, and formulate a project question. Perform the checks without altering the supplied values.</p>
<ol type="a">
<li>Verify that <code>Unique Key</code> contains no missing or duplicated identifiers. Explain what a duplicate would mean for the claimed observational unit.</li>
<li>Construct a frequency table for <code>Agency</code>. Compare the intended portal selection with the agency values actually delivered, and determine whether every row is an NYPD request.</li>
<li>Find the earliest and latest <code>Created Date</code>. Separately check for records before midnight on September 6 and at or after midnight on September 13. Explain why the upper boundary is exclusive. Report how many delivered records fail each boundary, show the failure counts in a small table, and summarize the dates and times of the out-of-window records. Retain them in the source data frame. Distinguish the intended portal filters from the checks you performed on its returned file.</li>
<li>Create a new data frame containing only requests in the intended interval. Produce a complete frequency table for <code>Problem (formerly Complaint Type)</code>. Then create a second data frame containing the illegal-parking requests and verify its dimensions. Explain why both filters belong in code rather than in undocumented manual edits to the CSV file.</li>
<li>For every column in the illegal-parking subset, report the number and percentage of missing values. Identify columns that are completely or almost completely missing. Separately report missingness in <code>Created Date</code>, <code>Closed Date</code>, <code>Incident Zip</code>, <code>Borough</code>, <code>Latitude</code>, and <code>Longitude</code>.</li>
<li>Check whether latitude and longitude are always missing together. Report their nonmissing ranges. Explain why plausible coordinate ranges can reveal obvious errors but cannot prove that every point lies within New York City.</li>
<li>Compare <code>Status</code> with the presence or absence of <code>Closed Date</code>. Determine whether every record whose status is not <code>Closed</code> lacks a closing time. Include a status-by-missingness contingency table and report any inconsistent rows without changing their values.</li>
<li>Verify that no closing time precedes its creation time. Summarize the elapsed time from creation to closure, and explain why it should be called closure time rather than response time unless additional documentation supports the latter interpretation.</li>
<li>Produce the complete frequency table for <code>Problem Detail (formerly Descriptor)</code>. Explain what the table reveals about variation hidden within the broader illegal-parking category.</li>
<li>Generate one project idea by the question-to-data route: begin with a domain concern, narrow it by unit, outcome, place, period, comparison, claim, and audience, and then assess whether this extract contains the needed evidence. Generate a second idea by the data-to-question route: begin with an observed frequency, anomaly, or comparison in your checks and connect it to a domain purpose. Label each question as descriptive, comparative, predictive, or causal, and identify additional data or assumptions it would require.</li>
<li>Select the stronger of your two questions as a possible project. Justify it using domain value, measurement fit, scope fit, and evidence fit. State one important claim that the project could not support.</li>
<li>Save the screened illegal-parking data frame as a persistent Feather file at a separate path such as <code>data/illegal_parking.feather</code> for later analysis. Reset inherited row-index labels while retaining <code>Unique Key</code>, then read the file back and report checks of its row count, columns, values, and data types. Record the source archive and both row filters in the derived file’s provenance; keep the ZIP archive unchanged.</li>
</ol>
</div>
<div id="exr-curate-311" class="theorem exercise">
<p><span class="theorem-title"><strong> 5.3</strong></span> Extend the quality checks into a documented cleaning plan. This optional problem bridges problem formulation and data preparation. Do not overwrite the source object or remove a record solely because it fails a warning-level check.</p>
<ol type="a">
<li>Read Tussey and Yan <span class="citation" data-cites="tussey2025principles">(<a href="#ref-tussey2025principles" role="doc-biblioref">2025</a>)</span>. Summarize the six curation principles and explain why transparent documentation is part of data quality. Then select <strong>two</strong> diagnostic areas for closer investigation: missing-value representations and category variants; timestamp parsing and chronological relationships; time heaping and closure durations; ZIP Code syntax and geographic validity; or potentially redundant fields. For each selected area, report the evidence, identify the records and fields in scope, and explain what the diagnostic can and cannot establish. Do not infer a correction from an anomaly alone.</li>
<li>Create a cleaning log for the issues you investigated. Include the affected variables, evidence, scope, proposed action, justification, and whether curator input is needed. Keep original values available. Translate at least four checks into reusable validation code, distinguish hard failures from warnings, and report each rule with the number of affected records.</li>
<li>Suppose that the NYC 311 data curator has invited feedback. Write three to five recommendations based on your evidence. Separate recommendations about definitions and documentation from those about automated validation or representation. Do not recommend a correction unless the evidence establishes what the corrected value should be.</li>
</ol>
</div>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-apache2026feather" class="csl-entry" role="listitem">
Apache Arrow Developers. (2026). <em>Feather file format</em>. <a href="https://arrow.apache.org/docs/python/feather.html">https://arrow.apache.org/docs/python/feather.html</a>
</div>
<div id="ref-bates2024from" class="csl-entry" role="listitem">
Bates, D., &amp; Yan, J. (2024). From <span>CSV</span> to <span>Arrow</span>: Creating a unified data set for efficient cross-platform analysis. <em>CHANCE</em>, <em>37</em>(4), 48–52. <a href="https://doi.org/10.1080/09332480.2024.2434443">https://doi.org/10.1080/09332480.2024.2434443</a>
</div>
<div id="ref-nycopendatand311" class="csl-entry" role="listitem">
NYC Open Data. (n.d.). <em>311 service requests from 2020 to present</em>. Retrieved September 27, 2026, from <a href="https://data.cityofnewyork.us/d/erm2-nwe9">https://data.cityofnewyork.us/d/erm2-nwe9</a>
</div>
<div id="ref-tussey2025principles" class="csl-entry" role="listitem">
Tussey, D., &amp; Yan, J. (2025). <em>Principles for open data curation: A case study with the new york city 311 service request data</em>. <a href="https://doi.org/10.48550/arXiv.2502.08649">https://doi.org/10.48550/arXiv.2502.08649</a>
</div>
<div id="ref-census2023zip" class="csl-entry" role="listitem">
U.S. Census Bureau. (2023). <em><span>ZIP</span> code tabulation areas (<span>ZCTAs</span>)</em>. <a href="https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html">https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html</a>
</div>
<div id="ref-yu2024veridical" class="csl-entry" role="listitem">
Yu, B., &amp; Barter, R. L. (2024). <em>Veridical data science: The practice of responsible data analysis and decision making</em>. The MIT Press. <a href="https://vdsbook.com/">https://vdsbook.com/</a>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/statds\.github\.io\/ids-book");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-python.html" class="pagination-link" aria-label="Python Practice">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Python Practice</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-wrangling.html" class="pagination-link" aria-label="Data Preparation">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Preparation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/statds/ids-book/edit/main/05-formulation.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/statds/ids-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>