<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Data Preparation – Introduction to Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-eda.html" rel="next">
<link href="./05-formulation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c935fea28ce5a425f876bb828138d8e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-wrangling.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Preparation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/statds/ids-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preliminaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Project Management</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reproducible Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Python Practice</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-formulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Problem Formulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-wrangling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Preparation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modeling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-ethics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Ethics</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#from-source-records-to-an-analysis-table" id="toc-from-source-records-to-an-analysis-table" class="nav-link active" data-scroll-target="#from-source-records-to-an-analysis-table"><span class="header-section-number">6.1</span> From Source Records to an Analysis Table</a></li>
  <li><a href="#recheck-scope-before-transforming" id="toc-recheck-scope-before-transforming" class="nav-link" data-scroll-target="#recheck-scope-before-transforming"><span class="header-section-number">6.2</span> Recheck Scope Before Transforming</a></li>
  <li><a href="#standardize-representations-conservatively" id="toc-standardize-representations-conservatively" class="nav-link" data-scroll-target="#standardize-representations-conservatively"><span class="header-section-number">6.3</span> Standardize Representations Conservatively</a></li>
  <li><a href="#derive-variables-from-documented-meanings" id="toc-derive-variables-from-documented-meanings" class="nav-link" data-scroll-target="#derive-variables-from-documented-meanings"><span class="header-section-number">6.4</span> Derive Variables from Documented Meanings</a></li>
  <li><a href="#sec-zcta-context-merge" id="toc-sec-zcta-context-merge" class="nav-link" data-scroll-target="#sec-zcta-context-merge"><span class="header-section-number">6.5</span> Merge Area-Level Context with Checks</a></li>
  <li><a href="#validate-the-prepared-data" id="toc-validate-the-prepared-data" class="nav-link" data-scroll-target="#validate-the-prepared-data"><span class="header-section-number">6.6</span> Validate the Prepared Data</a></li>
  <li><a href="#preparation-as-a-documented-argument" id="toc-preparation-as-a-documented-argument" class="nav-link" data-scroll-target="#preparation-as-a-documented-argument"><span class="header-section-number">6.7</span> Preparation as a Documented Argument</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/statds/ids-book/edit/main/06-wrangling.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/statds/ids-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-wrangling" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Preparation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Data preparation constructs an analysis table from acquired records while preserving the evidence needed to evaluate each transformation. The input in this chapter is the distributed NYPD-directed 311 archive and the scope defined in <a href="05-formulation.html" class="quarto-xref"><span>Chapter 5</span></a>. Its principal output is a request-level table with documented field names, derived closure hours, a creation-time category, and matched Census area context where a valid match exists. The domain, measurement, scope, and evidence checks in <a href="05-formulation.html#sec-formulation-checks" class="quarto-xref"><span>Section 5.1</span></a> determine which fields are retained and which operations require justification. A successful transformation need not make every value regular: an unmatched ZIP label or an unusual timestamp can be a finding about the source rather than a value to overwrite. The workflow therefore separates changes in representation from new analytical assumptions, checks that request identity and scope survive each stage, and records what remains uncertain before the prepared table is used for exploration or visualization.</p>
<section id="from-source-records-to-an-analysis-table" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="from-source-records-to-an-analysis-table"><span class="header-section-number">6.1</span> From Source Records to an Analysis Table</h2>
<p>Data preparation starts from a question and a retained source, not from an assumption that the downloaded table is already analysis-ready. The previous chapter established the observational unit, checked the requested time window, and selected illegal-parking requests. Here, those checks become input conditions for the preparation workflow: scope assertions detect a changed or incorrect input, while later checks verify that transformations preserve the intended records. The chapter then standardizes representations where the meaning is clear, derives variables needed for analysis, and considers geographic enrichment only when units and geographies align. The steps are iterative because a transformation can expose a problem or show that a question requires different data.</p>
<p>A preparation plan separates three classes of decisions because they have different implications for the resulting claim. <strong>Scope decisions</strong> select eligible observations and fields. <strong>Representation decisions</strong> encode a recorded value for reliable computation without changing its documented meaning, as when a ZIP Code is stored as text. <strong>Analytical decisions</strong> define new measurements or resolve uncertain values, as when a particular hour range is designated nighttime. Every class should leave an auditable record, but analytical choices especially require a rationale because they can change the outcome or comparison. The original ZIP archive remains unchanged. <a href="05-formulation.html" class="quarto-xref"><span>Chapter 5</span></a> demonstrated its acquisition and initial profile; the code below repeats only the import, timestamp parsing, and row filters needed for this chapter to run independently. Temporary Feather examples in that chapter do not provide an input here. Each subsequent stage creates a derived data frame and verifies the assumptions that its operation introduces.</p>
<div id="e6106aa9" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>data_path <span class="op">=</span> Path(<span class="st">"data"</span>) <span class="op">/</span> <span class="st">"311_nypd_lbdwk_2026.csv.zip"</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>requests <span class="op">=</span> pd.read_csv(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    data_path,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    compression<span class="op">=</span><span class="st">"zip"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    dtype<span class="op">=</span>{<span class="st">"Unique Key"</span>: <span class="st">"string"</span>, <span class="st">"Incident Zip"</span>: <span class="st">"string"</span>},</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    low_memory<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>date_format <span class="op">=</span> <span class="st">"%m/</span><span class="sc">%d</span><span class="st">/%Y %I:%M:%S %p"</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column <span class="kw">in</span> [<span class="st">"Created Date"</span>, <span class="st">"Closed Date"</span>]:</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    requests[column] <span class="op">=</span> pd.to_datetime(</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>        requests[column], <span class="bu">format</span><span class="op">=</span>date_format, errors<span class="op">=</span><span class="st">"coerce"</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> pd.Timestamp(<span class="st">"2026-09-06"</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>end <span class="op">=</span> pd.Timestamp(<span class="st">"2026-09-13"</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>parking <span class="op">=</span> requests.loc[</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    requests[<span class="st">"Created Date"</span>].between(start, end, inclusive<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    <span class="op">&amp;</span> requests[<span class="st">"Problem (formerly Complaint Type)"</span>].eq(<span class="st">"Illegal Parking"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>].copy()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The import block reconstructs the intended analysis scope without overwriting the downloaded archive. The half-open timestamp interval includes requests created on every day of the selected week and excludes those returned from the following Sunday; the problem condition restricts the subset to illegal-parking requests. The observational unit remains one service request, so a row restriction changes the eligible population but does not aggregate or validate individual observations. The explicit datetime format also exposes parsing failures as missing timestamps, which must be checked rather than silently interpreted as absent service activity. The resulting frame can still contain missing fields, unexpected category values, duplicate identifiers, or disagreements among geographic descriptors. Those issues require separate diagnostics before a derived variable or merge can be trusted. The subset also remains limited to NYPD-directed requests from one week, regardless of how consistently its columns are represented.</p>
</section>
<section id="recheck-scope-before-transforming" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="recheck-scope-before-transforming"><span class="header-section-number">6.2</span> Recheck Scope Before Transforming</h2>
<p>The compact scope report tests the conditions on which this preparation workflow depends. <a href="05-formulation.html#sec-initial-checks" class="quarto-xref"><span>Section 5.4</span></a> documented the delivered extract’s agency, timestamp, identifier, and missingness patterns; reproducing those diagnostic tables would add little to a chapter about transformation. The present check instead treats the expected row unit and filters as executable invariants: identifiers must be present and unique, creation times must fall within the selected half-open week, and every retained row must carry the illegal-parking problem label. These tests serve a different purpose from the initial profile. They detect a changed input file, an altered filter, or a parsing failure before derived columns are constructed. A failed invariant should prompt inspection of the source and the preparation code; it should not be repaired by automatically dropping records until the check passes. This chapter remains independently executable while the substantive diagnosis stays in the formulation chapter.</p>
<div id="f558829b" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>scope_checks <span class="op">=</span> pd.Series({</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"rows"</span>: <span class="bu">len</span>(parking),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"no missing request identifiers"</span>: <span class="kw">not</span> parking[<span class="st">"Unique Key"</span>].isna().<span class="bu">any</span>(),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"unique request identifiers"</span>: parking[<span class="st">"Unique Key"</span>].is_unique,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"all in intended week"</span>: parking[<span class="st">"Created Date"</span>].between(</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>        start, end, inclusive<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    ).<span class="bu">all</span>(),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"all illegal parking"</span>: parking[</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Problem (formerly Complaint Type)"</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    ].eq(<span class="st">"Illegal Parking"</span>).<span class="bu">all</span>(),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>}, name<span class="op">=</span><span class="st">"passed"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>scope_checks.to_frame()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">passed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">rows</th>
<td>13040</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">no missing request identifiers</th>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">unique request identifiers</th>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">all in intended week</th>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">all illegal parking</th>
<td>True</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The invariant report confirms that the selected requests and their identifiers remain intact before transformations. Coordinate completeness is not a condition for the ZIP-label merge below, because that operation uses the provider’s <code>Incident Zip</code> field rather than latitude and longitude. Removing requests without coordinates at this stage would therefore change the population for a reason unrelated to the planned join. A subsequent point map or distance calculation has a different eligibility rule and must report the resulting exclusions separately. An area match also cannot restore a missing point location: an area label identifies a region, while distance to a precinct requires a location and a specified distance metric. These examples illustrate why eligibility should be defined for each analytical quantity instead of imposed once as a generic complete-case filter.</p>
</section>
<section id="standardize-representations-conservatively" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="standardize-representations-conservatively"><span class="header-section-number">6.3</span> Standardize Representations Conservatively</h2>
<p>Representation changes make fields usable without asserting new facts about the observations. Dates should use datetime types, while ZIP Codes and request keys should remain strings because their digits are labels rather than measured magnitudes. Converting a ZIP Code such as <code>00501</code> to an integer would remove its leading zero; recoding a blank, <code>N/A</code>, and <code>Unspecified</code> to one missing value would be justified only if their documented meanings coincide. Column names require the same care. The NYC export uses spaces, punctuation, capitalization, and historical parenthetical wording; these labels are valid but inconvenient for repeated analysis. A derived table can use consistent names while the imported source and a complete source-to-analysis mapping retain the provider’s terminology. The mapping must be checked for collisions because two distinct source fields can normalize to the same string. A collision requires explicit disambiguation before either field is renamed.</p>
<p>Category standardization requires evidence about the meanings of values, not only a preference for uniform text. The frequency table in <a href="05-formulation.html#sec-problem-detail-counts" class="quarto-xref"><span>Section 5.7</span></a> established which problem details motivate the working comparison. The following code inspects the distinct source strings before any recoding. The observed leading labels are interpretable, and apparent similarity between two labels would not by itself establish that they describe the same reporting condition. A data dictionary or curator explanation would be needed before combining categories with different names. By contrast, the code below changes column <em>names</em> to make operations easier while leaving category <em>values</em> unchanged. Keeping those two decisions separate preserves the provider’s distinctions and allows later readers to evaluate a proposed recode against the source.</p>
<div id="cbeab347" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>detail_column <span class="op">=</span> <span class="st">"Problem Detail (formerly Descriptor)"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>observed_details <span class="op">=</span> (</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    parking[detail_column]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    .dropna()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    .drop_duplicates()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    .sort_values()</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    .reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    .rename(<span class="st">"observed detail"</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    .to_frame()</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>observed_details</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">observed detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Blocked Bike Lane</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Blocked Crosswalk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Blocked Hydrant</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Blocked Sidewalk</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Commercial Overnight Parking</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Detached Trailer</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Double Parked Blocking Traffic</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Double Parked Blocking Vehicle</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>License Plate Obscured</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Overnight Commercial Storage</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Paper License Plates</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Parking Permit Improper Use</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>Posted Parking Sign Violation</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>Unauthorized Bus Layover</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The following mapping converts all 44 labels to lowercase snake case and gives shorter analytical names to the fields used repeatedly below. The imported <code>parking</code> table retains the provider’s original labels; <code>analysis</code> is the derived table with renamed columns.</p>
<div id="a1daf954" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> re</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>name_map <span class="op">=</span> {</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    source_name: re.sub(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        <span class="vs">r"_</span><span class="op">+</span><span class="vs">"</span>, <span class="st">"_"</span>, re.sub(<span class="vs">r"</span><span class="pp">[^a-z0-9]</span><span class="op">+</span><span class="vs">"</span>, <span class="st">"_"</span>, source_name.lower())</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    ).strip(<span class="st">"_"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> source_name <span class="kw">in</span> parking.columns</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>name_map.update({</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Unique Key"</span>: <span class="st">"request_id"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Created Date"</span>: <span class="st">"created_at"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Closed Date"</span>: <span class="st">"closed_at"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Problem (formerly Complaint Type)"</span>: <span class="st">"problem"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Problem Detail (formerly Descriptor)"</span>: <span class="st">"problem_detail"</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Incident Zip"</span>: <span class="st">"incident_zip"</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Latitude"</span>: <span class="st">"latitude"</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Longitude"</span>: <span class="st">"longitude"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Status"</span>: <span class="st">"status"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>analysis_names <span class="op">=</span> pd.Index(name_map.values())</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> analysis_names.is_unique:</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"Column-name normalization produced a collision."</span>)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>name_mapping <span class="op">=</span> pd.DataFrame({</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"source_name"</span>: name_map.keys(),</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"analysis_name"</span>: name_map.values(),</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>analysis <span class="op">=</span> parking.rename(columns<span class="op">=</span>name_map).copy()</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>name_mapping</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">source_name</th>
<th data-quarto-table-cell-role="th">analysis_name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Unique Key</td>
<td>request_id</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Created Date</td>
<td>created_at</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Closed Date</td>
<td>closed_at</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Agency</td>
<td>agency</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Agency Name</td>
<td>agency_name</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Problem (formerly Complaint Type)</td>
<td>problem</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Problem Detail (formerly Descriptor)</td>
<td>problem_detail</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Additional Details</td>
<td>additional_details</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Location Type</td>
<td>location_type</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Incident Zip</td>
<td>incident_zip</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Incident Address</td>
<td>incident_address</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Street Name</td>
<td>street_name</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>Cross Street 1</td>
<td>cross_street_1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>Cross Street 2</td>
<td>cross_street_2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>Intersection Street 1</td>
<td>intersection_street_1</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">15</th>
<td>Intersection Street 2</td>
<td>intersection_street_2</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">16</th>
<td>Address Type</td>
<td>address_type</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17</th>
<td>City</td>
<td>city</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">18</th>
<td>Landmark</td>
<td>landmark</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">19</th>
<td>Facility Type</td>
<td>facility_type</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">20</th>
<td>Status</td>
<td>status</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">21</th>
<td>Due Date</td>
<td>due_date</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">22</th>
<td>Resolution Description</td>
<td>resolution_description</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">23</th>
<td>Resolution Action Updated Date</td>
<td>resolution_action_updated_date</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">24</th>
<td>Community Board</td>
<td>community_board</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">25</th>
<td>Council District</td>
<td>council_district</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">26</th>
<td>Police Precinct</td>
<td>police_precinct</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">27</th>
<td>BBL</td>
<td>bbl</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">28</th>
<td>Borough</td>
<td>borough</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">29</th>
<td>X Coordinate (State Plane)</td>
<td>x_coordinate_state_plane</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">30</th>
<td>Y Coordinate (State Plane)</td>
<td>y_coordinate_state_plane</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">31</th>
<td>Open Data Channel Type</td>
<td>open_data_channel_type</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">32</th>
<td>Park Facility Name</td>
<td>park_facility_name</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">33</th>
<td>Park Borough</td>
<td>park_borough</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">34</th>
<td>Vehicle Type</td>
<td>vehicle_type</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">35</th>
<td>Taxi Company Borough</td>
<td>taxi_company_borough</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">36</th>
<td>Taxi Pick Up Location</td>
<td>taxi_pick_up_location</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">37</th>
<td>Bridge Highway Name</td>
<td>bridge_highway_name</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">38</th>
<td>Bridge Highway Direction</td>
<td>bridge_highway_direction</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">39</th>
<td>Road Ramp</td>
<td>road_ramp</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">40</th>
<td>Bridge Highway Segment</td>
<td>bridge_highway_segment</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">41</th>
<td>Latitude</td>
<td>latitude</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">42</th>
<td>Longitude</td>
<td>longitude</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">43</th>
<td>Location</td>
<td>location</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="6db3092d" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>analysis[[</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"request_id"</span>, <span class="st">"created_at"</span>, <span class="st">"problem_detail"</span>, <span class="st">"incident_zip"</span>, <span class="st">"status"</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>]].head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">request_id</th>
<th data-quarto-table-cell-role="th">created_at</th>
<th data-quarto-table-cell-role="th">problem_detail</th>
<th data-quarto-table-cell-role="th">incident_zip</th>
<th data-quarto-table-cell-role="th">status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1906</th>
<td>70393841</td>
<td>2026-09-12 23:59:29</td>
<td>Blocked Hydrant</td>
<td>10467</td>
<td>Closed</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1915</th>
<td>70397706</td>
<td>2026-09-12 23:58:24</td>
<td>Posted Parking Sign Violation</td>
<td>11378</td>
<td>Closed</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1937</th>
<td>70390106</td>
<td>2026-09-12 23:56:57</td>
<td>Commercial Overnight Parking</td>
<td>11378</td>
<td>Closed</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1941</th>
<td>70394982</td>
<td>2026-09-12 23:56:38</td>
<td>Blocked Hydrant</td>
<td>10455</td>
<td>Closed</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1943</th>
<td>70387502</td>
<td>2026-09-12 23:56:33</td>
<td>Blocked Hydrant</td>
<td>10454</td>
<td>Closed</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The short display confirms that the derived table exposes analytical names while retaining the provider’s values. The mapping table above records the correspondence between the two schemas; it should accompany any exported analysis table so that a future reader can trace a variable back to its source. This distinction matters when a provider changes a label but not a definition, or retains a label while changing how a field is populated. Neither case can be resolved from normalized column names alone. A later comparison across agencies or years would require a data-dictionary review of field definitions and collection rules in addition to consistent code syntax. Thus, standardization improves the reliability of operations on the table without claiming that all similarly named values are measured in the same way.</p>
</section>
<section id="derive-variables-from-documented-meanings" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="derive-variables-from-documented-meanings"><span class="header-section-number">6.4</span> Derive Variables from Documented Meanings</h2>
<p>Derived variables translate recorded fields into measurements required by the question while making new assumptions explicit. Let <span class="math inline">\(C_i\)</span> and <span class="math inline">\(L_i\)</span> denote the recorded creation and closure timestamps for request <span class="math inline">\(i\)</span>. The derived value <span class="math inline">\(T_i=(L_i-C_i)/3600\)</span> is the elapsed interval in hours when the timestamp difference is measured in seconds and both times are available. Its validity requires successful parsing and a nonnegative chronology. The definition does not assert that an officer arrived at <span class="math inline">\(L_i\)</span> or that the reported condition ended then; those are distinct events that the archive does not measure. Keeping the two timestamps alongside <span class="math inline">\(T_i\)</span> permits an analyst to inspect a surprising value or revise the definition. A variable name such as <code>closure_hours</code> communicates the measurement more accurately than a label that would imply field response. The following calculation checks the resulting field before it is used as an outcome.</p>
<div id="53e61e66" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>analysis[<span class="st">"closure_hours"</span>] <span class="op">=</span> (</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    analysis[<span class="st">"closed_at"</span>] <span class="op">-</span> analysis[<span class="st">"created_at"</span>]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>).dt.total_seconds() <span class="op">/</span> <span class="dv">3600</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>duration_check <span class="op">=</span> pd.Series({</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"missing"</span>: analysis[<span class="st">"closure_hours"</span>].isna().<span class="bu">sum</span>(),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"negative"</span>: analysis[<span class="st">"closure_hours"</span>].lt(<span class="dv">0</span>).<span class="bu">sum</span>(),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"median"</span>: analysis[<span class="st">"closure_hours"</span>].median(),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"maximum"</span>: analysis[<span class="st">"closure_hours"</span>].<span class="bu">max</span>(),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>}, name<span class="op">=</span><span class="st">"value"</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>duration_check.to_frame()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">missing</th>
<td>0.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">negative</th>
<td>0.000000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">median</th>
<td>1.670833</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">maximum</th>
<td>199.825556</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The duration check distinguishes missing outcomes, impossible chronology, and unusually long but nonnegative intervals. A negative value contradicts the expected order of creation and closure if both timestamps refer to the same request timeline; its source should be inspected before exclusion because parsing or a later correction may explain it. A missing closure timestamp leaves the interval undefined, and substituting the observation date would invent a closure event. A large positive interval is not automatically erroneous because administrative closure may occur well after a report is made. The median and maximum in the report serve different diagnostic purposes: one characterizes the center, while the other prompts inspection of the upper tail. <a href="07-eda.html" class="quarto-xref"><span>Chapter 7</span></a> examines that distribution rather than imposing an arbitrary cutoff during preparation.</p>
<p>Time-of-day groups require a boundary that reflects the intended comparison. “Night” has no universal definition, so the example assigns requests created from 8 p.m. through 5:59 a.m. to nighttime and those from 6 a.m. through 7:59 p.m. to daytime. The code leaves a missing creation hour unclassified instead of treating it as daytime. This categorical field can support a simple comparison, but it compresses variation across hours and ignores differences among individual dates, including the holiday in the selected week. The original timestamp remains in the table so that an analyst can examine hourly patterns or repeat the comparison under a different boundary. If the substantive question concerns staffing or reporting conditions, the boundary should be justified with relevant domain information rather than adopted solely because the resulting groups have convenient sizes.</p>
<div id="55272b92" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>hour <span class="op">=</span> analysis[<span class="st">"created_at"</span>].dt.hour</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>analysis[<span class="st">"time_period"</span>] <span class="op">=</span> pd.Series(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    pd.NA, index<span class="op">=</span>analysis.index, dtype<span class="op">=</span><span class="st">"string"</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>analysis.loc[hour.between(<span class="dv">6</span>, <span class="dv">19</span>), <span class="st">"time_period"</span>] <span class="op">=</span> <span class="st">"day"</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>analysis.loc[hour.ge(<span class="dv">20</span>) <span class="op">|</span> hour.lt(<span class="dv">6</span>), <span class="st">"time_period"</span>] <span class="op">=</span> <span class="st">"night"</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>analysis[<span class="st">"time_period"</span>].value_counts(dropna<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>time_period
day      8977
night    4063
Name: count, dtype: int64[pyarrow]</code></pre>
</div>
</div>
</section>
<section id="sec-zcta-context-merge" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="sec-zcta-context-merge"><span class="header-section-number">6.5</span> Merge Area-Level Context with Checks</h2>
<p>An area-level merge attaches contextual measurements to request records only under an explicit geographic matching rule. The request table has one row per service request; the Census context table has one row per ZIP Code Tabulation Area (ZCTA). The provider’s <code>Incident Zip</code> is a postal ZIP Code label, whereas a ZCTA is a Census statistical area derived from address patterns. Equal five-digit strings permit a lookup but do not make the geographies identical, and some postal ZIP Codes have no corresponding ZCTA <span class="citation" data-cites="census2023zip">(<a href="#ref-census2023zip" role="doc-biblioref">U.S. Census Bureau, 2023</a>)</span>. The intended join is many requests to one context row, so a duplicate key on the right would incorrectly multiply requests. The reference period of the attached estimate also matters: a value measured before the request week describes earlier area context, not a contemporaneous attribute of an individual report. These conditions must be stated before the software merge is interpreted as evidence about place.</p>
<p>The supplied <code>data/zcta_context.csv</code> contains the 221 ZCTAs in NYC Open Data’s city list and their 2024 American Community Survey (ACS) five-year population and median household income estimates <span class="citation" data-cites="nycopendata2026zip census2026american">(<a href="#ref-nycopendata2026zip" role="doc-biblioref">NYC Open Data, 2026</a>; <a href="#ref-census2026american" role="doc-biblioref">U.S. Census Bureau, 2026</a>)</span>. It also records margins of error, an income top-coding indicator, and the estimate year. The provenance and conversion rules in <code>data/zcta_context.md</code> distinguish the Census estimates from the NYC boundary list used to select areas. These fields allow an analyst to check both the statistical meaning of an attached value and the geographic coverage of the lookup. The code verifies that each context key is a five-digit string, occurs once, and has the expected reference year before the merge. It then retains unmatched requests and reports them separately. The result is a documented link between labels, not an assertion that a postal area and its similarly named ZCTA have identical boundaries.</p>
<p>The NYC ZCTA selection comes from the <code>zcta5</code> column of the city’s published dataset, as the following acquisition code shows. The chapter uses the saved CSV during rendering so that a live web request cannot change its results. The complete extraction, including both ACS tables, is in <code>scripts/build_zcta_context.py</code>.</p>
<div id="f2a55dbc" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> io <span class="im">import</span> StringIO</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>zcta_source <span class="op">=</span> <span class="st">"https://data.cityofnewyork.us/resource/35j5-n34v.csv"</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>response <span class="op">=</span> requests.get(</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    zcta_source,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    params<span class="op">=</span>{<span class="st">"$select"</span>: <span class="st">"zcta5"</span>, <span class="st">"$limit"</span>: <span class="dv">5000</span>},</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    timeout<span class="op">=</span><span class="dv">60</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>response.raise_for_status()</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>city_zctas <span class="op">=</span> pd.read_csv(</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    StringIO(response.text), dtype<span class="op">=</span>{<span class="st">"zcta5"</span>: <span class="st">"string"</span>}</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>)[<span class="st">"zcta5"</span>].drop_duplicates()</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(city_zctas)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="060b7979" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>zcta_context <span class="op">=</span> pd.read_csv(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    Path(<span class="st">"data"</span>) <span class="op">/</span> <span class="st">"zcta_context.csv"</span>,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    dtype<span class="op">=</span>{<span class="st">"zcta"</span>: <span class="st">"string"</span>},</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>zcta_context[<span class="st">"zcta"</span>] <span class="op">=</span> zcta_context[<span class="st">"zcta"</span>].<span class="bu">str</span>.strip()</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> zcta_context[<span class="st">"zcta"</span>].isna().<span class="bu">any</span>():</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"The ZCTA lookup contains missing keys."</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> zcta_context[<span class="st">"zcta"</span>].<span class="bu">str</span>.fullmatch(<span class="vs">r"</span><span class="dv">\d</span><span class="op">{5}</span><span class="vs">"</span>).<span class="bu">all</span>():</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"ZCTA keys must be five-digit strings."</span>)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> zcta_context[<span class="st">"zcta"</span>].duplicated().<span class="bu">any</span>():</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"The ZCTA lookup must contain one row per key."</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> zcta_context[<span class="st">"acs_year"</span>].eq(<span class="dv">2024</span>).<span class="bu">all</span>():</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"The ZCTA lookup contains an unexpected ACS year."</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Match only syntactically five-digit request ZIP values. Do not silently</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="co"># pad or otherwise repair values that fail this check.</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>incident_zip <span class="op">=</span> analysis[<span class="st">"incident_zip"</span>].<span class="bu">str</span>.strip()</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>analysis[<span class="st">"zcta_match"</span>] <span class="op">=</span> incident_zip.where(</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    incident_zip.<span class="bu">str</span>.fullmatch(<span class="vs">r"</span><span class="dv">\d</span><span class="op">{5}</span><span class="vs">"</span>, na<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>contextual_analysis <span class="op">=</span> analysis.merge(</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>    zcta_context,</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"left"</span>,</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"zcta_match"</span>,</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>    right_on<span class="op">=</span><span class="st">"zcta"</span>,</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>    validate<span class="op">=</span><span class="st">"many_to_one"</span>,</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    indicator<span class="op">=</span><span class="st">"zcta_match_status"</span>,</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="bu">len</span>(contextual_analysis) <span class="op">!=</span> <span class="bu">len</span>(analysis):</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"The area-level join changed the request count."</span>)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> contextual_analysis[<span class="st">"request_id"</span>].is_unique:</span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"The area-level join duplicated request identifiers."</span>)</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>join_report <span class="op">=</span> pd.Series({</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">"requests"</span>: <span class="bu">len</span>(contextual_analysis),</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"matched requests"</span>: contextual_analysis[</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>        <span class="st">"zcta_match_status"</span></span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>    ].eq(<span class="st">"both"</span>).<span class="bu">sum</span>(),</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">"unmatched requests"</span>: contextual_analysis[</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>        <span class="st">"zcta_match_status"</span></span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>    ].eq(<span class="st">"left_only"</span>).<span class="bu">sum</span>(),</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>    <span class="st">"distinct unmatched ZIP values"</span>: contextual_analysis.loc[</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>        contextual_analysis[<span class="st">"zcta_match_status"</span>].eq(<span class="st">"left_only"</span>),</span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a>        <span class="st">"incident_zip"</span>,</span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a>    ].nunique(dropna<span class="op">=</span><span class="va">False</span>),</span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>}, name<span class="op">=</span><span class="st">"count"</span>)</span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a>join_report.to_frame()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">requests</th>
<td>13040</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">matched requests</th>
<td>13033</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">unmatched requests</th>
<td>7</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">distinct unmatched ZIP values</th>
<td>6</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The <code>validate</code> argument turns the assumed join cardinality into an executable check. If a lookup key is duplicated, the join can multiply request rows and inflate subsequent counts. The left join preserves requests that lack a match, and its indicator distinguishes matched from unmatched rows. Unmatched values should be examined for missing identifiers, non-ZCTA ZIP Codes, formatting differences, boundary mismatch, or a flawed lookup; they should not be silently dropped or repaired by adding leading zeros without evidence. In this extract, 13,033 of 13,040 illegal-parking requests match a listed ZCTA; the seven unmatched requests remain in the table for other analyses.</p>
<p>Area context permits new comparisons only after the target quantity has been specified at the appropriate unit. A ZCTA population estimate can serve as the denominator of requests per resident during the observation week, but the numerator counts reports rather than verified conditions and the denominator does not measure curb space or vehicle exposure. Income and other area characteristics can also be attached to requests, yet the repeated area value does not become an independently measured attribute of each reporter. If the question concerns differences among places, the analysis should first aggregate to one row per area and state how many requests support each area summary. If the question concerns individual behavior or a causal effect of neighborhood conditions, the available merge does not supply the necessary individual measurements or design. The join therefore expands the set of descriptive questions that can be asked while leaving reporting coverage, geographic mismatch, and temporal alignment as explicit limitations.</p>
</section>
<section id="validate-the-prepared-data" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="validate-the-prepared-data"><span class="header-section-number">6.6</span> Validate the Prepared Data</h2>
<p>Validation compares the prepared table with the input and with the stated analytical contract. The following checks require the request count and identifier uniqueness to survive filtering, renaming, derivation, and the area merge. They also require the retained timestamps and problem label to remain within the intended scope and confirm that the closure field exists. The join report above separately records unmatched keys, so a passing row count does not conceal incomplete geographic coverage. These checks detect specific implementation errors, but they cannot prove that a source value is true or that the selected week represents a broader population. If the prepared table is saved for later use, its schema, source-to-analysis name mapping, join report, and relevant invariants should be stored with it and checked again after reading it back. A successful write operation alone does not establish semantic or numerical validity.</p>
<div id="503b340b" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>prepared <span class="op">=</span> contextual_analysis.reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>final_checks <span class="op">=</span> pd.Series({</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"same request count"</span>: <span class="bu">len</span>(prepared) <span class="op">==</span> <span class="bu">len</span>(parking),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"unique request identifiers"</span>: prepared[<span class="st">"request_id"</span>].is_unique,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"all in intended week"</span>: prepared[<span class="st">"created_at"</span>].between(</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>        start, end, inclusive<span class="op">=</span><span class="st">"left"</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    ).<span class="bu">all</span>(),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"all illegal parking"</span>: prepared[<span class="st">"problem"</span>].eq(<span class="st">"Illegal Parking"</span>).<span class="bu">all</span>(),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"closure field present"</span>: <span class="st">"closure_hours"</span> <span class="kw">in</span> prepared.columns,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>}, name<span class="op">=</span><span class="st">"passed"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>final_checks.to_frame()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">passed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">same request count</th>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">unique request identifiers</th>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">all in intended week</th>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">all illegal parking</th>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">closure field present</th>
<td>True</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="preparation-as-a-documented-argument" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="preparation-as-a-documented-argument"><span class="header-section-number">6.7</span> Preparation as a Documented Argument</h2>
<p>The prepared table is a documented argument about which records and values can support the working question. Filters define scope, derived fields operationalize measurements, and the merge asserts a limited relationship between two geographic identifiers. The checks make those claims reviewable without implying that the source is error free. The exploratory and visualization chapters call a <a href="scripts/parking_requests.py">shared preparation function</a> for the screened request fields and closure hours; that compact function does not reproduce this chapter’s full 44-column mapping, time-period category, or enriched context table. Those later chapters construct only the additional fields their questions require. This division keeps the transformation logic visible here while avoiding a second long import and renaming sequence in each chapter. It also identifies a reproducibility obligation: if the screening rule or closure-time definition changes, the shared function and the explanations in this chapter must be reviewed together.</p>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<p>These exercises extend the import and checking work in the previous chapter. For the first exercise, begin with the screened table saved as <code>data/illegal_parking.feather</code> in that assignment. Do not repeat its import, scope filters, key checks, missingness report, or closure-time calculation. Keep the distributed ZIP archive unchanged, and include code with a concise explanation of each decision.</p>
<div id="exr-wrangle-311" class="theorem exercise">
<p><span class="theorem-title"><strong> 6.1</strong></span> Prepare an analysis table that can support exploratory comparisons and a subsequent logistic-regression analysis.</p>
<ol type="a">
<li>Inspect the observed values of <code>Problem Detail</code> and <code>Status</code>. Propose recoding only where the values support it. Show a mapping table, retain source values, and explain how unknown or rare values will be handled.</li>
<li>Rename only the fields needed for your analysis using a consistent convention. Show the old-to-new mapping, check for name collisions, and leave the imported table unchanged.</li>
<li>Merge <code>data/zcta_context.csv</code> using the documented ZIP-to-ZCTA match described in <a href="#sec-zcta-context-merge" class="quarto-xref"><span>Section 6.5</span></a>. Validate the merge cardinality, unmatched records, and preservation of one row per request. Explain why the match does not make ZIP Codes and ZCTAs equivalent.</li>
<li>Write a concise data dictionary for the fields used, including source or derived status, units, and limitations. Propose a binary closure-time outcome that marks requests taking at least two hours to close, and explain whether this threshold suits your question. Identify candidate predictors available when a request is created. Keep post-creation fields out of that predictor list and explain why.</li>
</ol>
</div>
<div id="exr-precinct-distance" class="theorem exercise">
<p><span class="theorem-title"><strong> 6.2</strong></span> Construct and validate a request-level measure of straight-line distance to the nearest NYPD precinct station.</p>
<ol type="a">
<li>Obtain a precinct roster from an authoritative source. Record the source, access date, precinct identifier, and address for each station. Explain why the precinct code in a 311 request identifies an administrative area but does not provide the station’s point location.</li>
<li>Geocode the precinct addresses and retain the original address, returned coordinates, geocoding method, and any match-quality information. Review unsuccessful or ambiguous matches rather than assigning coordinates automatically. Save the reviewed geocodes with their provenance so that a later render does not repeat external geocoding requests.</li>
<li>Check that station and request coordinates are present and plausible. Convert both sets of points to a suitable projected coordinate reference system before calculating distances. State the projection and units, and explain why distances calculated directly from longitude and latitude in degrees are not suitable.</li>
<li>For each request with coordinates, find the nearest station and calculate the straight-line distance in a stated unit. Retain the nearest station’s identifier and the distance in the derived table. Report how many requests could not receive a distance and why.</li>
<li>Compare the nearest station’s precinct identifier with the request’s <code>Police Precinct</code> value. Summarize matches and differences, and explain why distance to the nearest station and assignment to a precinct are distinct geographic measures.</li>
<li>Validate that the distance calculation did not change the request count or duplicate <code>Unique Key</code>. Discuss why straight-line distance is not travel distance, response time, or evidence that proximity causes faster closure.</li>
</ol>
</div>
<div id="exr-wrangle-open" class="theorem exercise">
<p><span class="theorem-title"><strong> 6.3</strong></span> Write a preparation plan for a different question suggested by the data. This exercise concerns the table and its checks; the visualization proposal in <a href="08-visualization.html" class="quarto-xref"><span>Chapter 8</span></a> addresses figure design.</p>
<ol type="a">
<li>State the question, intended audience, observational unit, outcome, and comparison. Specify whether the question is descriptive, comparative, predictive, or causal.</li>
<li>List the fields and any additional data required. For each proposed transformation, state its purpose, expected row unit, and a check that could detect an error.</li>
<li>Identify one issue that should be raised with a data curator rather than silently corrected. Draft a concise recommendation that distinguishes evidence from conjecture.</li>
<li>Describe what the prepared table will contain, what it will omit, and how its provenance will let another analyst reproduce the result.</li>
</ol>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-nycopendata2026zip" class="csl-entry" role="listitem">
NYC Open Data. (2026). <em><span>ZIP</span> code tabulation areas</em>. <a href="https://data.cityofnewyork.us/City-Government/ZIP-Code-Tabulation-Areas/35j5-n34v">https://data.cityofnewyork.us/City-Government/ZIP-Code-Tabulation-Areas/35j5-n34v</a>
</div>
<div id="ref-census2023zip" class="csl-entry" role="listitem">
U.S. Census Bureau. (2023). <em><span>ZIP</span> code tabulation areas (<span>ZCTAs</span>)</em>. <a href="https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html">https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html</a>
</div>
<div id="ref-census2026american" class="csl-entry" role="listitem">
U.S. Census Bureau. (2026). <em>2024 american community survey 5-year summary file</em>. <a href="https://www.census.gov/programs-surveys/acs/data/summary-file/2024.html">https://www.census.gov/programs-surveys/acs/data/summary-file/2024.html</a>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/statds\.github\.io\/ids-book");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-formulation.html" class="pagination-link" aria-label="Problem Formulation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Problem Formulation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-eda.html" class="pagination-link" aria-label="Exploratory Data Analysis">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/statds/ids-book/edit/main/06-wrangling.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/statds/ids-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>