<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Exploratory Data Analysis – Introduction to Data Science</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./08-visualization.html" rel="next">
<link href="./06-wrangling.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c935fea28ce5a425f876bb828138d8e6.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-eda.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Data Science</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/statds/ids-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preliminaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-git.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Project Management</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Reproducible Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Python Practice</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-formulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Problem Formulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-eda.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Modeling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-ethics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Ethics</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#principles-of-exploratory-data-analysis" id="toc-principles-of-exploratory-data-analysis" class="nav-link active" data-scroll-target="#principles-of-exploratory-data-analysis"><span class="header-section-number">7.1</span> Principles of exploratory data analysis</a></li>
  <li><a href="#from-formulation-to-exploration" id="toc-from-formulation-to-exploration" class="nav-link" data-scroll-target="#from-formulation-to-exploration"><span class="header-section-number">7.2</span> From formulation to exploration</a></li>
  <li><a href="#the-prepared-data-and-its-scope" id="toc-the-prepared-data-and-its-scope" class="nav-link" data-scroll-target="#the-prepared-data-and-its-scope"><span class="header-section-number">7.3</span> The prepared data and its scope</a></li>
  <li><a href="#the-distribution-of-closure-time" id="toc-the-distribution-of-closure-time" class="nav-link" data-scroll-target="#the-distribution-of-closure-time"><span class="header-section-number">7.4</span> The distribution of closure time</a></li>
  <li><a href="#comparing-problem-details" id="toc-comparing-problem-details" class="nav-link" data-scroll-target="#comparing-problem-details"><span class="header-section-number">7.5</span> Comparing problem details</a></li>
  <li><a href="#patterns-across-time-and-place" id="toc-patterns-across-time-and-place" class="nav-link" data-scroll-target="#patterns-across-time-and-place"><span class="header-section-number">7.6</span> Patterns across time and place</a></li>
  <li><a href="#associations-with-zcta-context" id="toc-associations-with-zcta-context" class="nav-link" data-scroll-target="#associations-with-zcta-context"><span class="header-section-number">7.7</span> Associations with ZCTA context</a></li>
  <li><a href="#hypothesis-tests-and-uncertainty" id="toc-hypothesis-tests-and-uncertainty" class="nav-link" data-scroll-target="#hypothesis-tests-and-uncertainty"><span class="header-section-number">7.8</span> Hypothesis tests and uncertainty</a></li>
  <li><a href="#sensitivity-checks" id="toc-sensitivity-checks" class="nav-link" data-scroll-target="#sensitivity-checks"><span class="header-section-number">7.9</span> Sensitivity checks</a></li>
  <li><a href="#revising-the-question" id="toc-revising-the-question" class="nav-link" data-scroll-target="#revising-the-question"><span class="header-section-number">7.10</span> Revising the question</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/statds/ids-book/edit/main/07-eda.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/statds/ids-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Exploratory data analysis (EDA) examines distributions, relationships, and irregularities before a final account of findings is written. Its purpose is to learn what the observed data can show, what they cannot show, and which questions deserve closer investigation <span class="citation" data-cites="nistndexploratory">(<a href="#ref-nistndexploratory" role="doc-biblioref">National Institute of Standards and Technology, n.d.</a>)</span>. This chapter first states principles that apply across datasets and then develops them through a case study. The next chapter treats visualization as a communication practice; here, plots support investigation alongside numerical summaries and checks of the records.</p>
<section id="principles-of-exploratory-data-analysis" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="principles-of-exploratory-data-analysis"><span class="header-section-number">7.1</span> Principles of exploratory data analysis</h2>
<p>Exploration begins by establishing what each row and variable represents, which records are eligible, and how the measurements were produced. Counts of rows, missing values, duplicate identifiers, implausible values, and failed joins can reveal limits that a polished summary conceals. Such checks do not serve only as preliminary cleaning: they define the set of observations to which a result applies. A decision to exclude an unusual value, for example, requires evidence about its validity and an account of how the exclusion changes the analysis. Retaining an original value and documenting a derived one makes that decision reviewable <span class="citation" data-cites="tussey2025principles">(<a href="#ref-tussey2025principles" role="doc-biblioref">Tussey &amp; Yan, 2025</a>)</span>. These practices connect EDA to the formulation and wrangling work of the preceding chapters, because an exploratory pattern is interpretable only when its units, coverage, and measurement are clear.</p>
<p>Exploration describes variation before reducing it to a single number. Center, spread, tails, missingness, and group sizes give different accounts of a distribution; a mean alone can conceal a long tail or distinct subgroups. Numerical summaries and plots should therefore be chosen to answer specific questions and checked against one another. Comparisons should also be repeated within relevant strata, such as time or place, when a pooled result may combine different processes. An unusual observation can prompt an inspection of its source, while a subgroup difference can prompt a revised question or a different summary. This cycle of inspection, comparison, and revision is the defining feature of EDA, rather than any particular chart or statistic <span class="citation" data-cites="nistndexploratory">(<a href="#ref-nistndexploratory" role="doc-biblioref">National Institute of Standards and Technology, n.d.</a>)</span>.</p>
<p>Exploration separates observed differences from claims about a broader process. A table can describe every record in its stated scope without assuming that those records form a random sample. A hypothesis test or interval adds a model for how other records might arise, and its interpretation depends on that model’s assumptions. When groups, cutoffs, or comparisons are chosen after viewing the data, their inferential status must be reported as exploratory. Statistical evidence also cannot repair missing coverage, uncertain measurement, or confounding. A useful exploratory report therefore records the choices that generated a pattern, examines whether reasonable alternatives change it, and states what additional data or design would be needed for a stronger claim <span class="citation" data-cites="wasserstein2016asa">(<a href="#ref-wasserstein2016asa" role="doc-biblioref">Wasserstein &amp; Lazar, 2016</a>)</span>.</p>
</section>
<section id="from-formulation-to-exploration" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="from-formulation-to-exploration"><span class="header-section-number">7.2</span> From formulation to exploration</h2>
<p>The case study examines NYPD illegal-parking requests prepared in Chapter 6. Its main question is how recorded closure-time distributions differ among the three most frequently reported problem details during September 6–12, 2026. Time, borough, and ZCTA comparisons provide context for the citywide result. A hypothesis test then illustrates the assumptions needed to move from a description of these records to an inferential claim.</p>
<p>The working question in Chapter 5 identifies a population of records, a time window, a measurement, and groups to compare. Its outcome is the elapsed time between each request’s recorded creation and closure timestamps. This quantity does not measure the time until an officer arrived or the time until a parking condition ended. The groups are values of the provider’s problem-detail field, and their frequencies are determined from this week. Thus, even a precise group difference describes recorded requests under the chosen scope. The four formulation checks in <a href="05-formulation.html#sec-formulation-checks" class="quarto-xref"><span>Section 5.1</span></a> remain useful: domain fit determines which comparisons matter, measurement fit governs the interpretation of closure time, scope fit limits the population described, and evidence fit governs the strength of a claim.</p>
<p>The analysis follows the general principles in a visible sequence: it checks eligible records and the outcome, summarizes the full distribution, compares the three detail groups, and then investigates variation across time and place. Each step can generate a revised question. The sequence also clarifies which comparisons came from the working formulation and which were motivated by patterns observed later.</p>
</section>
<section id="the-prepared-data-and-its-scope" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="the-prepared-data-and-its-scope"><span class="header-section-number">7.3</span> The prepared data and its scope</h2>
<p>The following code reconstructs the relevant columns from the distributed archive using the filters and timestamp rules established in Chapter 6. It creates a new table and retains the source archive unchanged. The five-digit ZIP check used later also follows the preceding chapter.</p>
<div id="beaf58ff" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>source <span class="op">=</span> Path(<span class="st">"data"</span>) <span class="op">/</span> <span class="st">"311_nypd_lbdwk_2026.csv.zip"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>requests <span class="op">=</span> pd.read_csv(</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    source,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    compression<span class="op">=</span><span class="st">"zip"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    dtype<span class="op">=</span>{<span class="st">"Unique Key"</span>: <span class="st">"string"</span>, <span class="st">"Incident Zip"</span>: <span class="st">"string"</span>},</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    low_memory<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>date_format <span class="op">=</span> <span class="st">"%m/</span><span class="sc">%d</span><span class="st">/%Y %I:%M:%S %p"</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> column <span class="kw">in</span> [<span class="st">"Created Date"</span>, <span class="st">"Closed Date"</span>]:</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    requests[column] <span class="op">=</span> pd.to_datetime(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>        requests[column], <span class="bu">format</span><span class="op">=</span>date_format, errors<span class="op">=</span><span class="st">"coerce"</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> pd.Timestamp(<span class="st">"2026-09-06"</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>end <span class="op">=</span> pd.Timestamp(<span class="st">"2026-09-13"</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>parking <span class="op">=</span> requests.loc[</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    requests[<span class="st">"Created Date"</span>].between(start, end, inclusive<span class="op">=</span><span class="st">"left"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="op">&amp;</span> requests[<span class="st">"Problem (formerly Complaint Type)"</span>].eq(<span class="st">"Illegal Parking"</span>),</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    [</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Unique Key"</span>, <span class="st">"Created Date"</span>, <span class="st">"Closed Date"</span>,</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Problem Detail (formerly Descriptor)"</span>, <span class="st">"Borough"</span>, <span class="st">"Incident Zip"</span>,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Latitude"</span>, <span class="st">"Longitude"</span>,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    ],</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>parking <span class="op">=</span> parking.rename(columns<span class="op">=</span>{</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Unique Key"</span>: <span class="st">"request_id"</span>,</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Created Date"</span>: <span class="st">"created_at"</span>,</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Closed Date"</span>: <span class="st">"closed_at"</span>,</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Problem Detail (formerly Descriptor)"</span>: <span class="st">"problem_detail"</span>,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Borough"</span>: <span class="st">"borough"</span>,</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Incident Zip"</span>: <span class="st">"incident_zip"</span>,</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Latitude"</span>: <span class="st">"latitude"</span>,</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Longitude"</span>: <span class="st">"longitude"</span>,</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>parking[<span class="st">"closure_hours"</span>] <span class="op">=</span> (</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    parking[<span class="st">"closed_at"</span>] <span class="op">-</span> parking[<span class="st">"created_at"</span>]</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>).dt.total_seconds() <span class="op">/</span> <span class="dv">3600</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>scope_check <span class="op">=</span> pd.Series({</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    <span class="st">"requests"</span>: <span class="bu">len</span>(parking),</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>    <span class="st">"unique identifiers"</span>: parking[<span class="st">"request_id"</span>].nunique(),</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>    <span class="st">"missing closure times"</span>: parking[<span class="st">"closure_hours"</span>].isna().<span class="bu">sum</span>(),</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    <span class="st">"negative closure times"</span>: parking[<span class="st">"closure_hours"</span>].lt(<span class="dv">0</span>).<span class="bu">sum</span>(),</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>    <span class="st">"missing coordinates"</span>: parking[[<span class="st">"latitude"</span>, <span class="st">"longitude"</span>]]</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>        .isna().<span class="bu">any</span>(axis<span class="op">=</span><span class="dv">1</span>).<span class="bu">sum</span>(),</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>}, name<span class="op">=</span><span class="st">"count"</span>)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>scope_check.to_frame()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">requests</th>
<td>13040</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">unique identifiers</th>
<td>13040</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">missing closure times</th>
<td>0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">negative closure times</th>
<td>0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">missing coordinates</th>
<td>99</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The screened table contains 13,040 requests, with unique identifiers and no missing or negative closure intervals. Ninety-nine requests lack at least one coordinate, but coordinates are unnecessary for the main comparison. These checks justify retaining all 13,040 requests for that comparison; a spatial analysis requiring point locations would have a smaller eligible set. The table includes reports made during one week rather than a random sample of all parking incidents, and its records may reflect differences in reporting as well as differences in agency processing.</p>
</section>
<section id="the-distribution-of-closure-time" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="the-distribution-of-closure-time"><span class="header-section-number">7.4</span> The distribution of closure time</h2>
<p>A distribution should be described by its center, spread, and tails before groups are compared. The mean is sensitive to long intervals, whereas the median marks the point below which half of the observed intervals fall. A quantile reports a position in the observed distribution. The table and figure below use all closure intervals for calculations. The figure stops at 24 hours so that the main body can be inspected; longer values remain in the numerical summary.</p>
<div id="3efef2ab" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>closure_summary <span class="op">=</span> parking[<span class="st">"closure_hours"</span>].agg(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"count"</span>, <span class="st">"mean"</span>, <span class="st">"median"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>]</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>).to_frame(<span class="st">"value"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> label, probability <span class="kw">in</span> [</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"25th percentile"</span>, <span class="fl">.25</span>), (<span class="st">"75th percentile"</span>, <span class="fl">.75</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"90th percentile"</span>, <span class="fl">.90</span>), (<span class="st">"99th percentile"</span>, <span class="fl">.99</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>]:</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    closure_summary.loc[label] <span class="op">=</span> parking[<span class="st">"closure_hours"</span>].quantile(probability)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>closure_summary <span class="op">=</span> closure_summary.rename(index<span class="op">=</span>{</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"count"</span>: <span class="st">"requests"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"mean"</span>: <span class="st">"mean (hours)"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"median"</span>: <span class="st">"median (hours)"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"min"</span>: <span class="st">"minimum (hours)"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"max"</span>: <span class="st">"maximum (hours)"</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"25th percentile"</span>: <span class="st">"25th percentile (hours)"</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"75th percentile"</span>: <span class="st">"75th percentile (hours)"</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"90th percentile"</span>: <span class="st">"90th percentile (hours)"</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"99th percentile"</span>: <span class="st">"99th percentile (hours)"</span>,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>closure_summary.<span class="bu">round</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">requests</th>
<td>13040.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">mean (hours)</th>
<td>3.50</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">median (hours)</th>
<td>1.67</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">minimum (hours)</th>
<td>0.01</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">maximum (hours)</th>
<td>199.83</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">25th percentile (hours)</th>
<td>0.70</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">75th percentile (hours)</th>
<td>4.03</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">90th percentile (hours)</th>
<td>8.73</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">99th percentile (hours)</th>
<td>23.58</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-fig-eda-closure" class="cell" data-fig-format="svg" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>ax.hist(parking[<span class="st">"closure_hours"</span>], bins<span class="op">=</span>np.arange(<span class="dv">0</span>, <span class="fl">24.5</span>, <span class="fl">.5</span>),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">"#4477aa"</span>, edgecolor<span class="op">=</span><span class="st">"white"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"Recorded closure time (hours)"</span>, ylabel<span class="op">=</span><span class="st">"Requests"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>       xlim<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">24</span>))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-eda-closure" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eda-closure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-eda_files/figure-html/fig-eda-closure-output-1.png" width="602" height="357" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eda-closure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Recorded closure times for eligible illegal-parking requests. The display stops at 24 hours; the numerical summary includes longer intervals.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The median closure interval is about 1.67 hours, while the mean is about 3.51 hours. The 90th percentile is about 8.73 hours, the 99th percentile is about 23.58 hours, and the maximum is nearly 200 hours. This right tail makes the mean substantially larger than the median. It also makes a statement such as “requests close in about two hours” incomplete: it describes a typical request but omits the upper tail. A large interval may be valid, a correction to a timestamp, or an operational exception; its presence alone does not establish an error. The next comparison therefore reports medians and quartiles alongside means.</p>
</section>
<section id="comparing-problem-details" class="level2" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="comparing-problem-details"><span class="header-section-number">7.5</span> Comparing problem details</h2>
<p>Group selection is an analytical decision. The working question asks about the three most frequent detail values in the eligible week, so the code computes those frequencies before summarizing closure time. It does not combine similar sounding labels or choose groups because their closure summaries appear different. Because the groups are selected from the same records being described, later tests remain exploratory.</p>
<div id="45678e52" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>top_details <span class="op">=</span> parking[<span class="st">"problem_detail"</span>].value_counts().head(<span class="dv">3</span>).index.tolist()</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>top <span class="op">=</span> parking.loc[parking[<span class="st">"problem_detail"</span>].isin(top_details)].copy()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>detail_summary <span class="op">=</span> top.groupby(<span class="st">"problem_detail"</span>)[<span class="st">"closure_hours"</span>].agg(</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    requests<span class="op">=</span><span class="st">"count"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    mean_hours<span class="op">=</span><span class="st">"mean"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    median_hours<span class="op">=</span><span class="st">"median"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    lower_quartile<span class="op">=</span><span class="kw">lambda</span> values: values.quantile(<span class="fl">.25</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    upper_quartile<span class="op">=</span><span class="kw">lambda</span> values: values.quantile(<span class="fl">.75</span>),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    ninetieth_percentile<span class="op">=</span><span class="kw">lambda</span> values: values.quantile(<span class="fl">.90</span>),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>).reindex(top_details)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>detail_summary.<span class="bu">round</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">requests</th>
<th data-quarto-table-cell-role="th">mean_hours</th>
<th data-quarto-table-cell-role="th">median_hours</th>
<th data-quarto-table-cell-role="th">lower_quartile</th>
<th data-quarto-table-cell-role="th">upper_quartile</th>
<th data-quarto-table-cell-role="th">ninetieth_percentile</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">problem_detail</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Blocked Hydrant</th>
<td>3711</td>
<td>4.13</td>
<td>2.05</td>
<td>0.87</td>
<td>5.14</td>
<td>10.59</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Posted Parking Sign Violation</th>
<td>3266</td>
<td>3.27</td>
<td>1.62</td>
<td>0.70</td>
<td>3.70</td>
<td>7.87</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Blocked Sidewalk</th>
<td>1874</td>
<td>2.76</td>
<td>1.18</td>
<td>0.46</td>
<td>3.03</td>
<td>6.99</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-fig-eda-detail-ecdf" class="cell" data-fig-format="svg" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> detail <span class="kw">in</span> top_details:</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    durations <span class="op">=</span> np.sort(top.loc[</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        top[<span class="st">"problem_detail"</span>].eq(detail), <span class="st">"closure_hours"</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    ].to_numpy())</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    fractions <span class="op">=</span> np.arange(<span class="dv">1</span>, <span class="bu">len</span>(durations) <span class="op">+</span> <span class="dv">1</span>) <span class="op">/</span> <span class="bu">len</span>(durations)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    ax.step(durations, fractions, where<span class="op">=</span><span class="st">"post"</span>, label<span class="op">=</span>detail)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"Recorded closure time (hours)"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>       ylabel<span class="op">=</span><span class="st">"Proportion closed by this time"</span>, xlim<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">24</span>), ylim<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-eda-detail-ecdf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eda-detail-ecdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="07-eda_files/figure-html/fig-eda-detail-ecdf-output-1.png" width="590" height="362" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eda-detail-ecdf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.2: Empirical cumulative distributions of closure time for the three most reported details. The horizontal axis stops at 24 hours.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Blocked Hydrant has the largest median of the three groups, about 2.05 hours, followed by Posted Parking Sign Violation at 1.62 hours and Blocked Sidewalk at 1.18 hours. The hydrant group’s median exceeds the sidewalk group’s by about 0.86 hours, or 52 minutes. Their distributions overlap substantially, so the difference in medians does not mean that every hydrant request took longer than every sidewalk request. The cumulative curves show the proportion closed by any time on the horizontal axis; they retain more distributional information than a comparison of three means. Neither the table nor the plot identifies why the groups differ.</p>
</section>
<section id="patterns-across-time-and-place" class="level2" data-number="7.6">
<h2 data-number="7.6" class="anchored" data-anchor-id="patterns-across-time-and-place"><span class="header-section-number">7.6</span> Patterns across time and place</h2>
<p>Temporal and geographic comparisons can reveal whether a pooled contrast combines distinct patterns. Creation date measures when a report entered the system, while closure time measures the subsequent interval; grouping by creation date does not assign a request to the date on which it closed. The following tables examine request counts by creation date and detail counts by borough. Each count describes recorded requests, not underlying parking violations.</p>
<div id="10be4196" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>daily_counts <span class="op">=</span> parking.groupby(parking[<span class="st">"created_at"</span>].dt.date).size()</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>daily_counts.to_frame(<span class="st">"requests"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">requests</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">created_at</th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">2026-09-06</th>
<td>1563</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2026-09-07</th>
<td>1644</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2026-09-08</th>
<td>1945</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2026-09-09</th>
<td>1935</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2026-09-10</th>
<td>2080</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2026-09-11</th>
<td>2039</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2026-09-12</th>
<td>1834</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="1966cef2" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>borough_counts <span class="op">=</span> pd.crosstab(top[<span class="st">"borough"</span>], top[<span class="st">"problem_detail"</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>borough_counts.loc[:, top_details]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">problem_detail</th>
<th data-quarto-table-cell-role="th">Blocked Hydrant</th>
<th data-quarto-table-cell-role="th">Posted Parking Sign Violation</th>
<th data-quarto-table-cell-role="th">Blocked Sidewalk</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">borough</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">BRONX</th>
<td>507</td>
<td>466</td>
<td>188</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">BROOKLYN</th>
<td>1595</td>
<td>1288</td>
<td>824</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">MANHATTAN</th>
<td>281</td>
<td>558</td>
<td>179</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">QUEENS</th>
<td>1274</td>
<td>865</td>
<td>649</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">STATEN ISLAND</th>
<td>54</td>
<td>89</td>
<td>34</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Recorded daily volume ranges from 1,563 on September 6 to 2,080 on September 10. The counts alone do not establish a weekday effect because they cover only one occurrence of each day of the week. The borough table shows that the mix of problem details also varies by place: Manhattan has more Posted Parking Sign Violation requests than Blocked Hydrant requests, whereas Brooklyn has the opposite ordering. Geographic composition can therefore affect the citywide comparison. A borough label still represents a broad area and cannot identify the practices of an individual precinct.</p>
</section>
<section id="associations-with-zcta-context" class="level2" data-number="7.7">
<h2 data-number="7.7" class="anchored" data-anchor-id="associations-with-zcta-context"><span class="header-section-number">7.7</span> Associations with ZCTA context</h2>
<p>Area context offers a second exploratory question, but it changes the unit of analysis. Chapter 6 joins a request’s postal ZIP string to a 2024 American Community Survey (ACS) estimate for a matching ZIP Code Tabulation Area (ZCTA). Postal ZIP Codes and ZCTAs are not identical geographies <span class="citation" data-cites="census2023zip">(<a href="#ref-census2023zip" role="doc-biblioref">U.S. Census Bureau, 2023</a>)</span>. The same estimate is repeated on every matched request in that area, so treating those copies as independent area observations would overstate the information. This section instead constructs one summary row per matched ZCTA and records how many requests support each area’s median.</p>
<div id="712e9d6b" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>context <span class="op">=</span> pd.read_csv(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    Path(<span class="st">"data"</span>) <span class="op">/</span> <span class="st">"zcta_context.csv"</span>, dtype<span class="op">=</span>{<span class="st">"zcta"</span>: <span class="st">"string"</span>}</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> context[<span class="st">"zcta"</span>].duplicated().<span class="bu">any</span>():</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">ValueError</span>(<span class="st">"ZCTA context must have one row per area."</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>zip_text <span class="op">=</span> parking[<span class="st">"incident_zip"</span>].<span class="bu">str</span>.strip()</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>parking[<span class="st">"zcta_match"</span>] <span class="op">=</span> zip_text.where(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    zip_text.<span class="bu">str</span>.fullmatch(<span class="vs">r"</span><span class="dv">\d</span><span class="op">{5}</span><span class="vs">"</span>, na<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>with_context <span class="op">=</span> parking.merge(</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    context,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    left_on<span class="op">=</span><span class="st">"zcta_match"</span>, right_on<span class="op">=</span><span class="st">"zcta"</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    how<span class="op">=</span><span class="st">"left"</span>, validate<span class="op">=</span><span class="st">"many_to_one"</span>, indicator<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>with_context[<span class="st">"_merge"</span>].value_counts()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>_merge
both          13033
left_only         7
right_only        0
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cc27f41c" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>areas <span class="op">=</span> with_context.loc[with_context[<span class="st">"_merge"</span>].eq(<span class="st">"both"</span>)].groupby(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"zcta"</span>, as_index<span class="op">=</span><span class="va">False</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>).agg(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    requests<span class="op">=</span>(<span class="st">"request_id"</span>, <span class="st">"size"</span>),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    median_closure_hours<span class="op">=</span>(<span class="st">"closure_hours"</span>, <span class="st">"median"</span>),</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    median_household_income<span class="op">=</span>(<span class="st">"median_household_income"</span>, <span class="st">"first"</span>),</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>eligible_areas <span class="op">=</span> areas.loc[</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    areas[<span class="st">"requests"</span>].ge(<span class="dv">20</span>) <span class="op">&amp;</span> areas[<span class="st">"median_household_income"</span>].notna()</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>eligible_areas[<span class="st">"income_quartile"</span>] <span class="op">=</span> pd.qcut(</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    eligible_areas[<span class="st">"median_household_income"</span>], <span class="dv">4</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>[<span class="st">"lowest"</span>, <span class="st">"lower-middle"</span>, <span class="st">"upper-middle"</span>, <span class="st">"highest"</span>],</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>area_summary <span class="op">=</span> eligible_areas.groupby(</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"income_quartile"</span>, observed<span class="op">=</span><span class="va">True</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>).agg(</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    areas<span class="op">=</span>(<span class="st">"zcta"</span>, <span class="st">"size"</span>),</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    requests<span class="op">=</span>(<span class="st">"requests"</span>, <span class="st">"sum"</span>),</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>    median_of_area_medians<span class="op">=</span>(<span class="st">"median_closure_hours"</span>, <span class="st">"median"</span>),</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>area_summary.<span class="bu">round</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">areas</th>
<th data-quarto-table-cell-role="th">requests</th>
<th data-quarto-table-cell-role="th">median_of_area_medians</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">income_quartile</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">lowest</th>
<td>38</td>
<td>3069</td>
<td>1.64</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">lower-middle</th>
<td>37</td>
<td>3361</td>
<td>2.32</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">upper-middle</th>
<td>37</td>
<td>3264</td>
<td>2.02</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">highest</th>
<td>37</td>
<td>3008</td>
<td>1.00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The join matches 13,033 of 13,040 requests. Among areas with at least 20 requests and a reported median household income, 149 ZCTAs enter the grouped comparison. Their median closure times differ across income quartiles, but the ordering is not monotone: the lower-middle quartile has a higher median of area medians than the lowest or upper-middle quartile. The minimum count of 20 is a transparent stability rule, not a guarantee of accurate area estimates. The ACS income values describe an earlier period and have sampling uncertainty; the request-to-ZCTA match also has geographic limits <span class="citation" data-cites="census2026american">(<a href="#ref-census2026american" role="doc-biblioref">U.S. Census Bureau, 2026</a>)</span>. This table supports a question about area-level association, not a conclusion about residents’ incomes or an income effect on individual requests.</p>
</section>
<section id="hypothesis-tests-and-uncertainty" class="level2" data-number="7.8">
<h2 data-number="7.8" class="anchored" data-anchor-id="hypothesis-tests-and-uncertainty"><span class="header-section-number">7.8</span> Hypothesis tests and uncertainty</h2>
<p>A hypothesis test can be part of EDA when its assumptions and limited purpose are explicit. Consider the median closure-time difference between Blocked Hydrant and Blocked Sidewalk requests. For the observed week, that difference is descriptive and needs no test. A test addresses a different question: under a model in which requests from the two detail groups have exchangeable closure-time distributions, how unusual would the observed difference be? The permutation calculation below pools the two groups and reallocates their labels while preserving their sizes. Its two-sided statistic is the absolute difference between medians. A bootstrap interval separately resamples requests within each group to show variability under an independent-request model.</p>
<div id="3a501624" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>hydrant <span class="op">=</span> top.loc[</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    top[<span class="st">"problem_detail"</span>].eq(<span class="st">"Blocked Hydrant"</span>), <span class="st">"closure_hours"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>].to_numpy()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>sidewalk <span class="op">=</span> top.loc[</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    top[<span class="st">"problem_detail"</span>].eq(<span class="st">"Blocked Sidewalk"</span>), <span class="st">"closure_hours"</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>].to_numpy()</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>observed_gap <span class="op">=</span> np.median(hydrant) <span class="op">-</span> np.median(sidewalk)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">2026</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>bootstrap_gaps <span class="op">=</span> np.array([</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    np.median(rng.choice(hydrant, size<span class="op">=</span><span class="bu">len</span>(hydrant), replace<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span> np.median(rng.choice(sidewalk, size<span class="op">=</span><span class="bu">len</span>(sidewalk), replace<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2000</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>interval <span class="op">=</span> np.quantile(bootstrap_gaps, [<span class="fl">.025</span>, <span class="fl">.975</span>])</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>combined <span class="op">=</span> np.concatenate([hydrant, sidewalk])</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>permuted_gaps <span class="op">=</span> np.array([</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>    np.median(shuffled[:<span class="bu">len</span>(hydrant)])</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span> np.median(shuffled[<span class="bu">len</span>(hydrant):])</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> shuffled <span class="kw">in</span> (rng.permutation(combined) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2000</span>))</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>extreme <span class="op">=</span> np.count_nonzero(np.<span class="bu">abs</span>(permuted_gaps) <span class="op">&gt;=</span> <span class="bu">abs</span>(observed_gap))</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> (extreme <span class="op">+</span> <span class="dv">1</span>) <span class="op">/</span> (<span class="bu">len</span>(permuted_gaps) <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>pd.Series({</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"observed median gap (hours)"</span>: observed_gap,</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"bootstrap lower endpoint (hours)"</span>: interval[<span class="dv">0</span>],</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">"bootstrap upper endpoint (hours)"</span>: interval[<span class="dv">1</span>],</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>    <span class="st">"permutation p-value"</span>: p_value,</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>}).to_frame(<span class="st">"value"</span>).<span class="bu">round</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">observed median gap (hours)</th>
<td>0.8649</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">bootstrap lower endpoint (hours)</th>
<td>0.7119</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">bootstrap upper endpoint (hours)</th>
<td>1.0156</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">permutation p-value</th>
<td>0.0005</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The observed median gap is about 0.865 hours, and the bootstrap interval is approximately 0.712 to 1.016 hours. The estimated permutation <span class="math inline">\(p\)</span>-value is about 0.0005, with the added one in the numerator and denominator preventing a reported zero from a finite set of permutations. These results show that the observed separation is large relative to these relabelings and resamples. They do not establish that the detail label causes a closure-time difference. Requests may be related through place, time, repeat reporting, or agency practice, and the analysis was chosen after inspection of this week. The bootstrap interval does not include uncertainty from coverage, measurement, or group selection. A <span class="math inline">\(p\)</span>-value should not be read as the probability that the null hypothesis is true or as a measure of practical importance <span class="citation" data-cites="wasserstein2016asa">(<a href="#ref-wasserstein2016asa" role="doc-biblioref">Wasserstein &amp; Lazar, 2016</a>)</span>.</p>
</section>
<section id="sensitivity-checks" class="level2" data-number="7.9">
<h2 data-number="7.9" class="anchored" data-anchor-id="sensitivity-checks"><span class="header-section-number">7.9</span> Sensitivity checks</h2>
<p>Sensitivity analysis asks whether a descriptive result depends strongly on a reasonable analytical choice. The first check removes intervals longer than 24 hours; this assesses the role of the upper tail without declaring those records invalid. The remaining checks repeat the hydrant-sidewalk comparison within all five boroughs. These summaries do not remove all possible confounding, but they show whether the citywide contrast has a similar form in several geographic subsets.</p>
<div id="e269916d" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> median_gap(frame):</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    left <span class="op">=</span> frame.loc[</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        frame[<span class="st">"problem_detail"</span>].eq(<span class="st">"Blocked Hydrant"</span>), <span class="st">"closure_hours"</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    right <span class="op">=</span> frame.loc[</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>        frame[<span class="st">"problem_detail"</span>].eq(<span class="st">"Blocked Sidewalk"</span>), <span class="st">"closure_hours"</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.Series({</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"hydrant_requests"</span>: <span class="bu">len</span>(left),</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"sidewalk_requests"</span>: <span class="bu">len</span>(right),</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"median_gap_hours"</span>: left.median() <span class="op">-</span> right.median(),</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="op">=</span> pd.DataFrame({</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"all requests"</span>: median_gap(top),</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"closure at most 24 hours"</span>: median_gap(</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>        top.loc[top[<span class="st">"closure_hours"</span>].le(<span class="dv">24</span>)]</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>}).T</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> borough <span class="kw">in</span> <span class="bu">sorted</span>(top[<span class="st">"borough"</span>].dropna().unique()):</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>    sensitivity.loc[borough.title()] <span class="op">=</span> median_gap(</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>        top.loc[top[<span class="st">"borough"</span>].eq(borough)]</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>sensitivity[[<span class="st">"hydrant_requests"</span>, <span class="st">"sidewalk_requests"</span>]] <span class="op">=</span> sensitivity[[</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"hydrant_requests"</span>, <span class="st">"sidewalk_requests"</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>]].astype(<span class="bu">int</span>)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>sensitivity.<span class="bu">round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">hydrant_requests</th>
<th data-quarto-table-cell-role="th">sidewalk_requests</th>
<th data-quarto-table-cell-role="th">median_gap_hours</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">all requests</th>
<td>3711</td>
<td>1874</td>
<td>0.865</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">closure at most 24 hours</th>
<td>3675</td>
<td>1861</td>
<td>0.848</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Bronx</th>
<td>507</td>
<td>188</td>
<td>0.095</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Brooklyn</th>
<td>1595</td>
<td>824</td>
<td>1.071</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Manhattan</th>
<td>281</td>
<td>179</td>
<td>-0.023</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Queens</th>
<td>1274</td>
<td>649</td>
<td>1.088</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Staten Island</th>
<td>54</td>
<td>34</td>
<td>2.635</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The all-request median gap is about 0.865 hours and changes little, to about 0.848 hours, after intervals above 24 hours are excluded. The geographic comparisons are less uniform: the gap is about 1.07 hours in Brooklyn and 1.09 hours in Queens, but only 0.10 hours in the Bronx and approximately zero in Manhattan. Staten Island has a larger gap, but its comparison uses only 54 hydrant and 34 sidewalk requests. Group sizes and possible differences in case mix or processing limit the interpretation of these contrasts. The pooled result therefore does not describe every borough equally well.</p>
</section>
<section id="revising-the-question" class="level2" data-number="7.10">
<h2 data-number="7.10" class="anchored" data-anchor-id="revising-the-question"><span class="header-section-number">7.10</span> Revising the question</h2>
<p>Exploration has answered the initial descriptive question for the recorded week: closure-time distributions differ among the three most reported details, with a long right tail and the largest median among Blocked Hydrant requests. It has also identified conditions for a more focused next analysis. A future question could compare those details within borough and creation-time strata across multiple weeks, while documenting changes in request volume and closure practices. A causal question about why closure times differ would require a design that addresses confounding and the meaning of the recorded outcome. The ZCTA analysis similarly motivates area-level questions but does not turn area income into a request-level explanation. EDA makes observed patterns and the limits of their interpretation explicit enough to guide that next question.</p>
</section>
<section id="exercises" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercises">Exercises</h2>
<p>These exercises use the distributed request archive and, where indicated, <code>data/zcta_context.csv</code>. Report the record counts behind each summary, state units and exclusions, and distinguish descriptive findings from claims about processes outside the observed week.</p>
<div id="exr-eda-time" class="theorem exercise">
<p><span class="theorem-title"><strong> 7.1</strong></span> Examine whether the closure-time comparison varies by the hour when a request was created.</p>
<ol type="a">
<li>Divide creation hours into four six-hour intervals, state their boundaries, and report the request count and median closure time for each interval.</li>
<li>Repeat the table for the three most frequent problem details. Identify one contrast that changes across intervals and compare its group sizes.</li>
<li>Explain why the tables cannot by themselves distinguish a time-of-day effect from changes in location, reporting behavior, or case mix.</li>
</ol>
</div>
<div id="exr-eda-area" class="theorem exercise">
<p><span class="theorem-title"><strong> 7.2</strong></span> Revisit the ZCTA comparison under alternative inclusion rules.</p>
<ol type="a">
<li>Construct one row per matched ZCTA with request count, median closure time, and ACS median household income. Report missing income values and explain why the area, rather than the request, is the observational unit here.</li>
<li>Compare the quartile summary using minimum request counts of 10, 20, and 40 per ZCTA. State how many areas and requests enter each version.</li>
<li>Assess whether the direction of the area-level association is stable. Describe at least two limitations of a postal ZIP to ZCTA string match.</li>
</ol>
</div>
<div id="exr-eda-inference" class="theorem exercise">
<p><span class="theorem-title"><strong> 7.3</strong></span> Evaluate a proposed claim that hydrant requests generally take longer to close than sidewalk requests.</p>
<ol type="a">
<li>Reproduce the observed median difference, bootstrap interval, and permutation calculation using a documented random seed.</li>
<li>Repeat the median comparison within each borough with at least 50 requests of each detail. Report the eligible group counts.</li>
<li>Write a conclusion that separates the observed week’s pattern, inference under the resampling assumptions, and the unsupported causal claim.</li>
</ol>
</div>
</section>
<section id="references" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="references">References</h2>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-nistndexploratory" class="csl-entry" role="listitem">
National Institute of Standards and Technology. (n.d.). <em>Exploratory data analysis</em>. Retrieved September 30, 2026, from <a href="https://itl.nist.gov/div898/handbook/eda/section1/eda11.htm">https://itl.nist.gov/div898/handbook/eda/section1/eda11.htm</a>
</div>
<div id="ref-tussey2025principles" class="csl-entry" role="listitem">
Tussey, D., &amp; Yan, J. (2025). <em>Principles for open data curation: A case study with the new york city 311 service request data</em>. <a href="https://doi.org/10.48550/arXiv.2502.08649">https://doi.org/10.48550/arXiv.2502.08649</a>
</div>
<div id="ref-census2023zip" class="csl-entry" role="listitem">
U.S. Census Bureau. (2023). <em><span>ZIP</span> code tabulation areas (<span>ZCTAs</span>)</em>. <a href="https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html">https://www.census.gov/programs-surveys/geography/guidance/geo-areas/zctas.html</a>
</div>
<div id="ref-census2026american" class="csl-entry" role="listitem">
U.S. Census Bureau. (2026). <em>2024 american community survey 5-year summary file</em>. <a href="https://www.census.gov/programs-surveys/acs/data/summary-file/2024.html">https://www.census.gov/programs-surveys/acs/data/summary-file/2024.html</a>
</div>
<div id="ref-wasserstein2016asa" class="csl-entry" role="listitem">
Wasserstein, R. L., &amp; Lazar, N. A. (2016). The <span>ASA</span> statement on <span class="math inline">\(p\)</span>-values: Context, process, and purpose. <em>The American Statistician</em>, <em>70</em>(2), 129–133. <a href="https://doi.org/10.1080/00031305.2016.1154108">https://doi.org/10.1080/00031305.2016.1154108</a>
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/statds\.github\.io\/ids-book");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./06-wrangling.html" class="pagination-link" aria-label="Data Wrangling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./08-visualization.html" class="pagination-link" aria-label="Visualization">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualization</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/statds/ids-book/edit/main/07-eda.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/statds/ids-book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>